OrbbecSDK: E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/h/Device.h File Reference
Device.h File Reference
Device-related functions, including operations such as obtaining and creating a device, setting and obtaining device property, and obtaining sensors.
#include "ObTypes.h"
#include "Property.h"
#include "MultipleDevices.h"
#include "Advanced.h"
Macros
#define ob_device_list_device_count ob_device_list_get_count
#define ob_device_list_get_extension_info ob_device_info_get_extension_info
#define ob_device_upgrade ob_device_update_firmware
#define ob_device_upgrade_from_data ob_device_update_firmware_from_data
#define ob_device_get_supported_property ob_device_get_supported_property_item
#define ob_device_state_changed ob_device_set_state_changed_callback
#define ob_device_info_name ob_device_info_get_name
#define ob_device_info_pid ob_device_info_get_pid
#define ob_device_info_vid ob_device_info_get_vid
#define ob_device_info_uid ob_device_info_get_uid
#define ob_device_info_serial_number ob_device_info_get_serial_number
#define ob_device_info_firmware_version ob_device_info_get_firmware_version
#define ob_device_info_connection_type ob_device_info_get_connection_type
#define ob_device_info_ip_address ob_device_info_get_ip_address
#define ob_device_info_hardware_version ob_device_info_get_hardware_version
#define ob_device_info_supported_min_sdk_version ob_device_info_get_supported_min_sdk_version
#define ob_device_info_asicName ob_device_info_get_asicName
#define ob_device_info_device_type ob_device_info_get_device_type
#define ob_device_list_get_device_count ob_device_list_get_count
#define ob_camera_param_list_count ob_camera_param_list_get_count
Functions
OB_EXPORT void ob_delete_device (ob_device *device, ob_error **error)
Delete a device.
OB_EXPORT ob_sensor_list * ob_device_get_sensor_list (const ob_device *device, ob_error **error)
List all sensors.
OB_EXPORT ob_sensor * ob_device_get_sensor (ob_device *device, ob_sensor_type type, ob_error **error)
Get a device's sensor.
OB_EXPORT void ob_device_set_int_property (ob_device *device, ob_property_id property_id, int32_t value, ob_error **error)
Set an integer type of device property.
OB_EXPORT int32_t ob_device_get_int_property (ob_device *device, ob_property_id property_id, ob_error **error)
Get an integer type of device property.
OB_EXPORT ob_int_property_range ob_device_get_int_property_range (ob_device *device, ob_property_id property_id, ob_error **error)
Get the integer type of device property range.
OB_EXPORT void ob_device_set_float_property (ob_device *device, ob_property_id property_id, float value, ob_error **error)
Set a float type of device property.
OB_EXPORT float ob_device_get_float_property (ob_device *device, ob_property_id property_id, ob_error **error)
Get a float type of device property.
OB_EXPORT ob_float_property_range ob_device_get_float_property_range (ob_device *device, ob_property_id property_id, ob_error **error)
Get the float type of device property range.
OB_EXPORT void ob_device_set_bool_property (ob_device *device, ob_property_id property_id, bool value, ob_error **error)
Set a boolean type of device property.
OB_EXPORT bool ob_device_get_bool_property (ob_device *device, ob_property_id property_id, ob_error **error)
Get a boolean type of device property.
OB_EXPORT ob_bool_property_range ob_device_get_bool_property_range (ob_device *device, ob_property_id property_id, ob_error **error)
Get the boolean type of device property range.
OB_EXPORT void ob_device_set_structured_data (ob_device *device, ob_property_id property_id, const uint8_t *data, uint32_t data_size, ob_error **error)
Set structured data.
OB_EXPORT void ob_device_get_structured_data (ob_device *device, ob_property_id property_id, uint8_t *data, uint32_t *data_size, ob_error **error)
Get structured data of a device property.
OB_EXPORT void ob_device_get_raw_data (ob_device *device, ob_property_id property_id, ob_get_data_callback cb, void *user_data, ob_error **error)
Get raw data of a device property.
OB_EXPORT void ob_device_write_customer_data (ob_device *device, const void *data, uint32_t data_size, ob_error **error)
Set customer data.
OB_EXPORT void ob_device_read_customer_data (ob_device *device, void *data, uint32_t *data_size, ob_error **error)
Get customer data of a device property.
OB_EXPORT uint32_t ob_device_get_supported_property_count (const ob_device *device, ob_error **error)
Get the number of properties supported by the device.
OB_EXPORT ob_property_item ob_device_get_supported_property_item (const ob_device *device, uint32_t index, ob_error **error)
Get the type of property supported by the device.
OB_EXPORT bool ob_device_is_property_supported (const ob_device *device, ob_property_id property_id, ob_permission_type permission, ob_error **error)
Check if a device property permission is supported.
OB_EXPORT bool ob_device_is_global_timestamp_supported (const ob_device *device, ob_error **error)
Check if the device supports global timestamp.
OB_EXPORT void ob_device_enable_global_timestamp (ob_device *device, bool enable, ob_error **error)
Enable or disable global timestamp.
OB_EXPORT void ob_device_update_firmware (ob_device *device, const char *path, ob_device_fw_update_callback callback, bool async, void *user_data, ob_error **error)
Update the device firmware.
OB_EXPORT void ob_device_update_firmware_from_data (ob_device *device, const uint8_t *data, uint32_t data_size, ob_device_fw_update_callback callback, bool async, void *user_data, ob_error **error)
Update the device firmware from data.
OB_EXPORT void ob_device_update_optional_depth_presets (ob_device *device, const char file_path_list[][OB_PATH_MAX], uint8_t path_count, ob_device_fw_update_callback callback, void *user_data, ob_error **error)
Update the device optional depth presets.
OB_EXPORT void ob_device_reboot (ob_device *device, ob_error **error)
Device reboot.
OB_EXPORT ob_device_state ob_device_get_device_state (const ob_device *device, ob_error **error)
Get the current device status.
OB_EXPORT void ob_device_set_state_changed_callback (ob_device *device, ob_device_state_callback callback, void *user_data, ob_error **error)
Set the device state changed callback.
OB_EXPORT void ob_device_enable_heartbeat (ob_device *device, bool enable, ob_error **error)
Enable or disable the device heartbeat.
OB_EXPORT void ob_device_send_and_receive_data (ob_device *device, const uint8_t *send_data, uint32_t send_data_size, uint8_t *receive_data, uint32_t *receive_data_size, ob_error **error)
Send data to the device and receive data from the device.
OB_EXPORT ob_device_info * ob_device_get_device_info (const ob_device *device, ob_error **error)
Get device information.
OB_EXPORT void ob_delete_device_info (ob_device_info *info, ob_error **error)
Delete device information.
OB_EXPORT const char * ob_device_info_get_name (const ob_device_info *info, ob_error **error)
Get device name.
OB_EXPORT int ob_device_info_get_pid (const ob_device_info *info, ob_error **error)
Get device pid.
OB_EXPORT int ob_device_info_get_vid (const ob_device_info *info, ob_error **error)
Get device vid.
OB_EXPORT const char * ob_device_info_get_uid (const ob_device_info *info, ob_error **error)
Get device uid.
OB_EXPORT const char * ob_device_info_get_serial_number (const ob_device_info *info, ob_error **error)
Get device serial number.
OB_EXPORT const char * ob_device_info_get_firmware_version (const ob_device_info *info, ob_error **error)
Get the firmware version number.
OB_EXPORT const char * ob_device_info_get_connection_type (const ob_device_info *info, ob_error **error)
Get the device connection type.
OB_EXPORT const char * ob_device_info_get_ip_address (const ob_device_info *info, ob_error **error)
Get the device IP address.
OB_EXPORT const char * ob_device_info_get_hardware_version (const ob_device_info *info, ob_error **error)
Get the hardware version number.
OB_EXPORT bool ob_device_is_extension_info_exist (const ob_device *device, const char *info_key, ob_error **error)
Check if the device extension information exists.
OB_EXPORT const char * ob_device_get_extension_info (const ob_device *device, const char *info_key, ob_error **error)
Get the device extension information.
OB_EXPORT const char * ob_device_info_get_supported_min_sdk_version (const ob_device_info *info, ob_error **error)
Get the minimum SDK version number supported by the device.
OB_EXPORT const char * ob_device_info_get_asicName (const ob_device_info *info, ob_error **error)
Get the chip name.
OB_EXPORT ob_device_type ob_device_info_get_device_type (const ob_device_info *info, ob_error **error)
Get the device type.
OB_EXPORT void ob_delete_device_list (ob_device_list *list, ob_error **error)
Delete a device list.
OB_EXPORT uint32_t ob_device_list_get_count (const ob_device_list *list, ob_error **error)
Get the number of devices.
OB_EXPORT const char * ob_device_list_get_device_name (const ob_device_list *list, uint32_t index, ob_error **error)
Get device name.
OB_EXPORT int ob_device_list_get_device_pid (const ob_device_list *list, uint32_t index, ob_error **error)
Get the pid of the specified device.
OB_EXPORT int ob_device_list_get_device_vid (const ob_device_list *list, uint32_t index, ob_error **error)
Get the vid of the specified device.
OB_EXPORT const char * ob_device_list_get_device_uid (const ob_device_list *list, uint32_t index, ob_error **error)
Get the uid of the specified device.
OB_EXPORT const char * ob_device_list_get_device_serial_number (const ob_device_list *list, uint32_t index, ob_error **error)
Get the serial number of the specified device.
OB_EXPORT const char * ob_device_list_get_device_connection_type (const ob_device_list *list, uint32_t index, ob_error **error)
Get device connection type.
OB_EXPORT const char * ob_device_list_get_device_ip_address (const ob_device_list *list, uint32_t index, ob_error **error)
Get device ip address.
OB_EXPORT const char * ob_device_list_get_device_local_mac (const ob_device_list *list, uint32_t index, ob_error **error)
Get device local mac address.
OB_EXPORT ob_device * ob_device_list_get_device (const ob_device_list *list, uint32_t index, ob_error **error)
Create a device.
OB_EXPORT ob_device * ob_device_list_get_device_by_serial_number (const ob_device_list *list, const char *serial_number, ob_error **error)
Create a device.
OB_EXPORT ob_device * ob_device_list_get_device_by_uid (const ob_device_list *list, const char *uid, ob_error **error)
Create device by uid.
OB_EXPORT ob_camera_param_list * ob_device_get_calibration_camera_param_list (ob_device *device, ob_error **error)
Get the original parameter list of camera calibration saved on the device.
OB_EXPORT uint32_t ob_camera_param_list_get_count (ob_camera_param_list *param_list, ob_error **error)
Get the number of camera parameter lists.
OB_EXPORT ob_camera_param ob_camera_param_list_get_param (ob_camera_param_list *param_list, uint32_t index, ob_error **error)
Get camera parameters from the camera parameter list.
OB_EXPORT void ob_delete_camera_param_list (ob_camera_param_list *param_list, ob_error **error)
Delete the camera parameter list.
Detailed Description
Device-related functions, including operations such as obtaining and creating a device, setting and obtaining device property, and obtaining sensors.
Definition in file Device.h.
Macro Definition Documentation
ob_device_list_device_count
#define ob_device_list_device_count ob_device_list_get_count
Definition at line 667 of file Device.h.
ob_device_list_get_extension_info
#define ob_device_list_get_extension_info ob_device_info_get_extension_info
Definition at line 668 of file Device.h.
ob_device_upgrade
#define ob_device_upgrade ob_device_update_firmware
Definition at line 669 of file Device.h.
ob_device_upgrade_from_data
#define ob_device_upgrade_from_data ob_device_update_firmware_from_data
Definition at line 670 of file Device.h.
ob_device_get_supported_property
#define ob_device_get_supported_property ob_device_get_supported_property_item
Definition at line 671 of file Device.h.
ob_device_state_changed
#define ob_device_state_changed ob_device_set_state_changed_callback
Definition at line 672 of file Device.h.
ob_device_info_name
#define ob_device_info_name ob_device_info_get_name
Definition at line 673 of file Device.h.
ob_device_info_pid
#define ob_device_info_pid ob_device_info_get_pid
Definition at line 674 of file Device.h.
ob_device_info_vid
#define ob_device_info_vid ob_device_info_get_vid
Definition at line 675 of file Device.h.
ob_device_info_uid
#define ob_device_info_uid ob_device_info_get_uid
Definition at line 676 of file Device.h.
ob_device_info_serial_number
#define ob_device_info_serial_number ob_device_info_get_serial_number
Definition at line 677 of file Device.h.
ob_device_info_firmware_version
#define ob_device_info_firmware_version ob_device_info_get_firmware_version
Definition at line 678 of file Device.h.
ob_device_info_connection_type
#define ob_device_info_connection_type ob_device_info_get_connection_type
Definition at line 679 of file Device.h.
ob_device_info_ip_address
#define ob_device_info_ip_address ob_device_info_get_ip_address
Definition at line 680 of file Device.h.
ob_device_info_hardware_version
#define ob_device_info_hardware_version ob_device_info_get_hardware_version
Definition at line 681 of file Device.h.
ob_device_info_supported_min_sdk_version
#define ob_device_info_supported_min_sdk_version ob_device_info_get_supported_min_sdk_version
Definition at line 682 of file Device.h.
ob_device_info_asicName
#define ob_device_info_asicName ob_device_info_get_asicName
Definition at line 683 of file Device.h.
ob_device_info_device_type
#define ob_device_info_device_type ob_device_info_get_device_type
Definition at line 684 of file Device.h.
ob_device_list_get_device_count
#define ob_device_list_get_device_count ob_device_list_get_count
Definition at line 685 of file Device.h.
ob_camera_param_list_count
#define ob_camera_param_list_count ob_camera_param_list_get_count
Definition at line 686 of file Device.h.
Function Documentation
ob_delete_device()
OB_EXPORT void ob_delete_device (ob_device * device, ob_error ** error)
Delete a device.
Parameters
[in] device The device to be deleted.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::operator=(), and ob::Device::~Device().
ob_device_get_sensor_list()
OB_EXPORT ob_sensor_list * ob_device_get_sensor_list (const ob_device * device, ob_error ** error)
List all sensors.
Parameters
[in] device The device object.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_sensor_list* The list of all sensors.
Referenced by ob::Device::getSensorList().
ob_device_get_sensor()
OB_EXPORT ob_sensor * ob_device_get_sensor (ob_device * device, ob_sensor_type type, ob_error ** error)
Get a device's sensor.
Parameters
[in] device The device object.
[in] type The type of sensor to get.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_sensor* The acquired sensor.
Referenced by ob::Device::getSensor().
ob_device_set_int_property()
OB_EXPORT void ob_device_set_int_property (ob_device * device, ob_property_id property_id, int32_t value, ob_error ** error)
Set an integer type of device property.
Parameters
[in] device The device object.
[in] property_id The ID of the property to be set.
[in] value The property value to be set.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::setIntProperty().
ob_device_get_int_property()
OB_EXPORT int32_t ob_device_get_int_property (ob_device * device, ob_property_id property_id, ob_error ** error)
Get an integer type of device property.
Parameters
[in] device The device object.
[in] property_id The property ID.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int32_t The property value.
Referenced by ob::Device::getIntProperty().
ob_device_get_int_property_range()
OB_EXPORT ob_int_property_range ob_device_get_int_property_range (ob_device * device, ob_property_id property_id, ob_error ** error)
Get the integer type of device property range.
Parameters
[in] device The device object.
[in] property_id The property id.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The property range.
Referenced by ob::Device::getIntPropertyRange().
ob_device_set_float_property()
OB_EXPORT void ob_device_set_float_property (ob_device * device, ob_property_id property_id, float value, ob_error ** error)
Set a float type of device property.
Parameters
[in] device The device object.
[in] property_id The ID of the property to be set.
[in] value The property value to be set.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::setFloatProperty().
ob_device_get_float_property()
OB_EXPORT float ob_device_get_float_property (ob_device * device, ob_property_id property_id, ob_error ** error)
Get a float type of device property.
Parameters
[in] device The device object.
[in] property_id The property ID.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
float The property value.
Referenced by ob::Device::getFloatProperty().
ob_device_get_float_property_range()
OB_EXPORT ob_float_property_range ob_device_get_float_property_range (ob_device * device, ob_property_id property_id, ob_error ** error)
Get the float type of device property range.
Parameters
[in] device The device object.
[in] property_id The property id.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The property range.
Referenced by ob::Device::getFloatPropertyRange().
ob_device_set_bool_property()
OB_EXPORT void ob_device_set_bool_property (ob_device * device, ob_property_id property_id, bool value, ob_error ** error)
Set a boolean type of device property.
Parameters
[in] device The device object.
[in] property_id The ID of the property to be set.
[in] value The property value to be set.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::setBoolProperty().
ob_device_get_bool_property()
OB_EXPORT bool ob_device_get_bool_property (ob_device * device, ob_property_id property_id, ob_error ** error)
Get a boolean type of device property.
Parameters
[in] device The device object.
[in] property_id The property ID.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
bool The property value.
Referenced by ob::Device::getBoolProperty().
ob_device_get_bool_property_range()
OB_EXPORT ob_bool_property_range ob_device_get_bool_property_range (ob_device * device, ob_property_id property_id, ob_error ** error)
Get the boolean type of device property range.
Parameters
[in] device The device object.
[in] property_id The property id.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The property range.
Referenced by ob::Device::getBoolPropertyRange().
ob_device_set_structured_data()
OB_EXPORT void ob_device_set_structured_data (ob_device * device, ob_property_id property_id, const uint8_t * data, uint32_t data_size, ob_error ** error)
Set structured data.
Parameters
[in] device The device object.
[in] property_id The ID of the property to be set.
[in] data The property data to be set.
[in] data_size The size of the property to be set.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::setStructuredData().
ob_device_get_structured_data()
OB_EXPORT void ob_device_get_structured_data (ob_device * device, ob_property_id property_id, uint8_t * data, uint32_t * data_size, ob_error ** error)
Get structured data of a device property.
Parameters
[in] device The device object.
[in] property_id The ID of the property.
[out] data The obtained property data.
[out] data_size The size of the obtained property data.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::getStructuredData().
ob_device_get_raw_data()
OB_EXPORT void ob_device_get_raw_data (ob_device * device, ob_property_id property_id, ob_get_data_callback cb, void * user_data, ob_error ** error)
Get raw data of a device property.
Parameters
[in] device The device object.
[in] property_id The ID of the property.
[out] cb The get data callback.
[out] user_data User-defined data that will be returned in the callback.
[out] error Pointer to an error object that will be set if an error occurs.
ob_device_write_customer_data()
OB_EXPORT void ob_device_write_customer_data (ob_device * device, const void * data, uint32_t data_size, ob_error ** error)
Set customer data.
Parameters
[in] device The device object.
[in] data The property data to be set.
[in] data_size The size of the property to be set,the maximum length cannot exceed 65532 bytes.
[out] error Log error messages.
Referenced by ob::Device::writeCustomerData().
ob_device_read_customer_data()
OB_EXPORT void ob_device_read_customer_data (ob_device * device, void * data, uint32_t * data_size, ob_error ** error)
Get customer data of a device property.
Parameters
[in] device The device object.
[out] data The obtained property data.
[out] data_size The size of the obtained property data.
[out] error Log error messages.
Referenced by ob::Device::readCustomerData().
ob_device_get_supported_property_count()
OB_EXPORT uint32_t ob_device_get_supported_property_count (const ob_device * device, ob_error ** error)
Get the number of properties supported by the device.
Parameters
[in] device The device object.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The number of properties supported by the device.
Referenced by ob::Device::getSupportedPropertyCount().
ob_device_get_supported_property_item()
OB_EXPORT ob_property_item ob_device_get_supported_property_item (const ob_device * device, uint32_t index, ob_error ** error)
Get the type of property supported by the device.
Parameters
[in] device The device object.
[in] index The property index.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The type of property supported by the device.
Referenced by ob::Device::getSupportedProperty().
ob_device_is_property_supported()
OB_EXPORT bool ob_device_is_property_supported (const ob_device * device, ob_property_id property_id, ob_permission_type permission, ob_error ** error)
Check if a device property permission is supported.
Parameters
[in] device The device object.
[in] property_id The property id.
[in] permission The type of permission that needs to be interpreted.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
Whether the property permission is supported.
Referenced by ob::Device::isPropertySupported().
ob_device_is_global_timestamp_supported()
OB_EXPORT bool ob_device_is_global_timestamp_supported (const ob_device * device, ob_error ** error)
Check if the device supports global timestamp.
Parameters
[in] device The device object.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
bool Whether the device supports global timestamp.
Referenced by ob::Device::isGlobalTimestampSupported().
ob_device_enable_global_timestamp()
OB_EXPORT void ob_device_enable_global_timestamp (ob_device * device, bool enable, ob_error ** error)
Enable or disable global timestamp.
Parameters
device The device object.
enable Whether to enable global timestamp.
error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::enableGlobalTimestamp().
ob_device_update_firmware()
OB_EXPORT void ob_device_update_firmware (ob_device * device, const char * path, ob_device_fw_update_callback callback, bool async, void * user_data, ob_error ** error)
Update the device firmware.
Parameters
[in] device The device object.
[in] path The firmware path.
[in] callback The firmware upgrade progress callback.
[in] async Whether to execute asynchronously.
[in] user_data User-defined data that will be returned in the callback.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::updateFirmware().
ob_device_update_firmware_from_data()
OB_EXPORT void ob_device_update_firmware_from_data (ob_device * device, const uint8_t * data, uint32_t data_size, ob_device_fw_update_callback callback, bool async, void * user_data, ob_error ** error)
Update the device firmware from data.
Parameters
[in] device The device object.
[in] data The firmware file data.
[in] data_size The firmware file size.
[in] callback The firmware upgrade progress callback.
[in] async Whether to execute asynchronously.
[in] user_data User-defined data that will be returned in the callback.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::updateFirmwareFromData().
ob_device_update_optional_depth_presets()
OB_EXPORT void ob_device_update_optional_depth_presets (ob_device * device, const char file_path_list[][OB_PATH_MAX], uint8_t path_count, ob_device_fw_update_callback callback, void * user_data, ob_error ** error)
Update the device optional depth presets.
Parameters
[in] device The device object.
[in] file_path_list A list(2D array) of preset file paths, each up to OB_PATH_MAX characters.
[in] path_count The number of the preset file paths.
[in] callback The preset upgrade progress callback.
[in] user_data User-defined data that will be returned in the callback.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::updateOptionalDepthPresets().
ob_device_reboot()
OB_EXPORT void ob_device_reboot (ob_device * device, ob_error ** error)
Device reboot.
Attention
The device will be disconnected and reconnected. After the device is disconnected, the interface access to the device handle may be abnormal. Please use the ob_delete_device interface to delete the handle directly. After the device is reconnected, it can be obtained again.
Parameters
[in] device Device object
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::reboot().
ob_device_get_device_state()
OB_EXPORT ob_device_state ob_device_get_device_state (const ob_device * device, ob_error ** error)
Get the current device status.
Parameters
[in] device The device object.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device_state The device state information.
Referenced by ob::Device::getDeviceState().
ob_device_set_state_changed_callback()
OB_EXPORT void ob_device_set_state_changed_callback (ob_device * device, ob_device_state_callback callback, void * user_data, ob_error ** error)
Set the device state changed callback.
Parameters
[in] device The device object.
[in] callback The callback function to be called when the device status changes.
[in] user_data User-defined data that will be returned in the callback.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::setDeviceStateChangedCallback().
ob_device_enable_heartbeat()
OB_EXPORT void ob_device_enable_heartbeat (ob_device * device, bool enable, ob_error ** error)
Enable or disable the device heartbeat.
After enable the device heartbeat, the sdk will start a thread to send heartbeat signal to the device error every 3 seconds.
Attention
If the device does not receive the heartbeat signal for a long time, it will be disconnected and rebooted.
Parameters
[in] device The device object.
[in] enable Whether to enable the device heartbeat.
error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::enableHeartbeat().
ob_device_send_and_receive_data()
OB_EXPORT void ob_device_send_and_receive_data (ob_device * device, const uint8_t * send_data, uint32_t send_data_size, uint8_t * receive_data, uint32_t * receive_data_size, ob_error ** error)
Send data to the device and receive data from the device.
This is a factory and debug function, which can be used to send and receive data from the device. The data format is secret and belongs to the device vendor.
Parameters
[in] device The device object.
[in] send_data The data to be sent to the device.
[in] send_data_size The size of the data to be sent to the device.
[out] receive_data The data received from the device.
[in,out] receive_data_size Pass in the expected size of the receive data, and return the actual size of the received data.
error Pointer to an error object that will be set if an error occurs.
Referenced by ob::Device::sendAndReceiveData().
ob_device_get_device_info()
OB_EXPORT ob_device_info * ob_device_get_device_info (const ob_device * device, ob_error ** error)
Get device information.
Parameters
[in] device The device to obtain information from.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device_info* The device information.
Referenced by ob::Device::getDeviceInfo().
ob_delete_device_info()
OB_EXPORT void ob_delete_device_info (ob_device_info * info, ob_error ** error)
Delete device information.
Parameters
[in] info The device information to be deleted.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::DeviceInfo::~DeviceInfo().
ob_device_info_get_name()
OB_EXPORT const char * ob_device_info_get_name (const ob_device_info * info, ob_error ** error)
Get device name.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* return the device name
Referenced by ob::DeviceInfo::getName().
ob_device_info_get_pid()
OB_EXPORT int ob_device_info_get_pid (const ob_device_info * info, ob_error ** error)
Get device pid.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int return the device pid
Referenced by ob::DeviceInfo::getPid().
ob_device_info_get_vid()
OB_EXPORT int ob_device_info_get_vid (const ob_device_info * info, ob_error ** error)
Get device vid.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int return device vid
Referenced by ob::DeviceInfo::getVid().
ob_device_info_get_uid()
OB_EXPORT const char * ob_device_info_get_uid (const ob_device_info * info, ob_error ** error)
Get device uid.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* return device uid
Referenced by ob::DeviceInfo::getUid().
ob_device_info_get_serial_number()
OB_EXPORT const char * ob_device_info_get_serial_number (const ob_device_info * info, ob_error ** error)
Get device serial number.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* return device serial number
Referenced by ob::DeviceInfo::getSerialNumber().
ob_device_info_get_firmware_version()
OB_EXPORT const char * ob_device_info_get_firmware_version (const ob_device_info * info, ob_error ** error)
Get the firmware version number.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int return the firmware version number
Referenced by ob::DeviceInfo::getFirmwareVersion().
ob_device_info_get_connection_type()
OB_EXPORT const char * ob_device_info_get_connection_type (const ob_device_info * info, ob_error ** error)
Get the device connection type.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The connection type, currently supports: "USB", "USB1.0", "USB1.1", "USB2.0", "USB2.1", "USB3.0", "USB3.1", "USB3.2", "Ethernet"
Referenced by ob::DeviceInfo::getConnectionType().
ob_device_info_get_ip_address()
OB_EXPORT const char * ob_device_info_get_ip_address (const ob_device_info * info, ob_error ** error)
Get the device IP address.
Attention
Only valid for network devices, otherwise it will return "0.0.0.0"
Parameters
info Device Information
error Pointer to an error object that will be set if an error occurs.
Returns
const char* The IP address, such as "192.168.1.10"
Referenced by ob::DeviceInfo::getIpAddress().
ob_device_info_get_hardware_version()
OB_EXPORT const char * ob_device_info_get_hardware_version (const ob_device_info * info, ob_error ** error)
Get the hardware version number.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The hardware version number
Referenced by ob::DeviceInfo::getHardwareVersion().
ob_device_is_extension_info_exist()
OB_EXPORT bool ob_device_is_extension_info_exist (const ob_device * device, const char * info_key, ob_error ** error)
Check if the device extension information exists.
Parameters
device The device object.
info_key The key of the device extension information.
error Pointer to an error object that will be set if an error occurs.
Returns
bool Whether the device extension information exists.
Referenced by ob::Device::isExtensionInfoExist().
ob_device_get_extension_info()
OB_EXPORT const char * ob_device_get_extension_info (const ob_device * device, const char * info_key, ob_error ** error)
Get the device extension information.
Extension information is a set of key-value pair of string, user cat get the information by the key.
Parameters
[in] device The device object.
[in] info_key The key of the device extension information.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The device extension information
Referenced by ob::Device::getExtensionInfo().
ob_device_info_get_supported_min_sdk_version()
OB_EXPORT const char * ob_device_info_get_supported_min_sdk_version (const ob_device_info * info, ob_error ** error)
Get the minimum SDK version number supported by the device.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The minimum SDK version number supported by the device
Referenced by ob::DeviceInfo::getSupportedMinSdkVersion().
ob_device_info_get_asicName()
OB_EXPORT const char * ob_device_info_get_asicName (const ob_device_info * info, ob_error ** error)
Get the chip name.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The ASIC name
Referenced by ob::DeviceInfo::getAsicName().
ob_device_info_get_device_type()
OB_EXPORT ob_device_type ob_device_info_get_device_type (const ob_device_info * info, ob_error ** error)
Get the device type.
Parameters
[in] info Device Information
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device_type The device type
Referenced by ob::DeviceInfo::getDeviceType().
ob_delete_device_list()
OB_EXPORT void ob_delete_device_list (ob_device_list * list, ob_error ** error)
Delete a device list.
Parameters
[in] list The device list object to be deleted.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::DeviceList::~DeviceList().
ob_device_list_get_count()
OB_EXPORT uint32_t ob_device_list_get_count (const ob_device_list * list, ob_error ** error)
Get the number of devices.
Parameters
[in] list Device list object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
uint32_t return the number of devices
Referenced by ob::DeviceList::getCount().
ob_device_list_get_device_name()
OB_EXPORT const char * ob_device_list_get_device_name (const ob_device_list * list, uint32_t index, ob_error ** error)
Get device name.
Parameters
[in] list Device list object
[in] index Device index
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* return device name
Referenced by ob::DeviceList::getName().
ob_device_list_get_device_pid()
OB_EXPORT int ob_device_list_get_device_pid (const ob_device_list * list, uint32_t index, ob_error ** error)
Get the pid of the specified device.
Parameters
[in] list Device list object
[in] index Device index
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int return the device pid
Referenced by ob::DeviceList::getPid().
ob_device_list_get_device_vid()
OB_EXPORT int ob_device_list_get_device_vid (const ob_device_list * list, uint32_t index, ob_error ** error)
Get the vid of the specified device.
Parameters
[in] list Device list object
[in] index Device index
[out] error Pointer to an error object that will be set if an error occurs.
Returns
int return device vid
Referenced by ob::DeviceList::getVid().
ob_device_list_get_device_uid()
OB_EXPORT const char * ob_device_list_get_device_uid (const ob_device_list * list, uint32_t index, ob_error ** error)
Get the uid of the specified device.
Parameters
[in] list Device list object
[in] index Device index
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* return the device uid
Referenced by ob::DeviceList::getUid().
ob_device_list_get_device_serial_number()
OB_EXPORT const char * ob_device_list_get_device_serial_number (const ob_device_list * list, uint32_t index, ob_error ** error)
Get the serial number of the specified device.
Parameters
[in] list Device list object.
[in] index Device index.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* The device UID.
Referenced by ob::DeviceList::getSerialNumber().
ob_device_list_get_device_connection_type()
OB_EXPORT const char * ob_device_list_get_device_connection_type (const ob_device_list * list, uint32_t index, ob_error ** error)
Get device connection type.
Parameters
[in] list Device list object
[in] index Device index
[out] error Pointer to an error object that will be set if an error occurs.
Returns
const char* returns the device connection type, currently supports: "USB", "USB1.0", "USB1.1", "USB2.0", "USB2.1", "USB3.0", "USB3.1", "USB3.2", "Ethernet"
Referenced by ob::DeviceList::getConnectionType().
ob_device_list_get_device_ip_address()
OB_EXPORT const char * ob_device_list_get_device_ip_address (const ob_device_list * list, uint32_t index, ob_error ** error)
Get device ip address.
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
list Device list object
index Device index
error Pointer to an error object that will be set if an error occurs.
Returns
const char* returns the device ip address, such as "192.168.1.10"
Referenced by ob::DeviceList::getIpAddress().
ob_device_list_get_device_local_mac()
OB_EXPORT const char * ob_device_list_get_device_local_mac (const ob_device_list * list, uint32_t index, ob_error ** error)
Get device local mac address.
Attention
Only valid for network devices, otherwise it will return "0:0:0:0:0:0".
Parameters
list Device list object
index Device index
error Pointer to an error object that will be set if an error occurs.
Returns
const char* returns the device mac address
Referenced by ob::DeviceList::getLocalMacAddress().
ob_device_list_get_device()
OB_EXPORT ob_device * ob_device_list_get_device (const ob_device_list * list, uint32_t index, ob_error ** error)
Create a device.
Attention
If the device has already been acquired and created elsewhere, repeated acquisitions will return an error.
Parameters
[in] list Device list object.
[in] index The index of the device to create.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device* The created device.
Referenced by ob::DeviceList::getDevice().
ob_device_list_get_device_by_serial_number()
OB_EXPORT ob_device * ob_device_list_get_device_by_serial_number (const ob_device_list * list, const char * serial_number, ob_error ** error)
Create a device.
Attention
If the device has already been acquired and created elsewhere, repeated acquisitions will return an error.
Parameters
[in] list Device list object.
[in] serial_number The serial number of the device to create.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device* The created device.
Referenced by ob::DeviceList::getDeviceBySN().
ob_device_list_get_device_by_uid()
OB_EXPORT ob_device * ob_device_list_get_device_by_uid (const ob_device_list * list, const char * uid, ob_error ** error)
Create device by uid.
On Linux platform, for usb device, the uid of the device is composed of bus-port-dev, for example 1-1.2-1. But the SDK will remove the dev number and only keep the bus-port as the uid to create the device, for example 1-1.2, so that we can create a device connected to the specified USB port. Similarly, users can also directly pass in bus-port as uid to create device.
For GMSL device, the uid is GMSL port with "gmsl2-" prefix, for example gmsl2-1.
Attention
If the device has already been acquired and created elsewhere, repeated acquisitions will return an error.
Parameters
[in] list Device list object.
[in] uid The UID of the device to create.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_device* The created device.
Referenced by ob::DeviceList::getDeviceByUid().
ob_device_get_calibration_camera_param_list()
OB_EXPORT ob_camera_param_list * ob_device_get_calibration_camera_param_list (ob_device * device, ob_error ** error)
Get the original parameter list of camera calibration saved on the device.
Attention
The parameters in the list do not correspond to the current open-stream configuration.You need to select the parameters according to the actual situation, and may need to do scaling, mirroring and other processing. Non-professional users are recommended to use the ob_pipeline_get_camera_param() interface.
Parameters
[in] device The device object.
[out] error Log error messages.
Returns
ob_camera_param_list The camera parameter list.
Referenced by ob::Device::getCalibrationCameraParamList().
ob_camera_param_list_get_count()
OB_EXPORT uint32_t ob_camera_param_list_get_count (ob_camera_param_list * param_list, ob_error ** error)
Get the number of camera parameter lists.
Parameters
[in] param_list Camera parameter list
[out] error Log error messages
Returns
uint32_t The number of lists
Referenced by ob::CameraParamList::getCount().
ob_camera_param_list_get_param()
OB_EXPORT ob_camera_param ob_camera_param_list_get_param (ob_camera_param_list * param_list, uint32_t index, ob_error ** error)
Get camera parameters from the camera parameter list.
Parameters
[in] param_list Camera parameter list
[in] index Parameter index
[out] error Log error messages
Returns
ob_camera_param The camera parameters. Since it returns the structure object directly, there is no need to provide a delete interface.
Referenced by ob::CameraParamList::getCameraParam().
ob_delete_camera_param_list()
OB_EXPORT void ob_delete_camera_param_list (ob_camera_param_list * param_list, ob_error ** error)
Delete the camera parameter list.
Parameters
[in] param_list Camera parameter list
[out] error Log error messages
Referenced by ob::CameraParamList::~CameraParamList().