OrbbecSDK: E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/h/RecordPlayback.h File Reference
RecordPlayback.h File Reference
#include "Device.h"
Functions
OB_EXPORT ob_record_device * ob_create_record_device (ob_device *device, const char *file_path, bool compression_enabled, ob_error **error)
Create a recording device for the specified device with a specified file path and compression enabled.
OB_EXPORT void ob_delete_record_device (ob_record_device *recorder, ob_error **error)
Delete a recording device.
OB_EXPORT void ob_record_device_pause (ob_record_device *recorder, ob_error **error)
Pause recording on the specified recording device.
OB_EXPORT void ob_record_device_resume (ob_record_device *recorder, ob_error **error)
Resume recording on the specified recording device.
OB_EXPORT ob_device * ob_create_playback_device (const char *file_path, ob_error **error)
Create a playback device for the specified file path.
OB_EXPORT void ob_playback_device_pause (ob_device *player, ob_error **error)
Pause playback on the specified playback device.
OB_EXPORT void ob_playback_device_resume (ob_device *player, ob_error **error)
Resume playback on the specified playback device.
OB_EXPORT void ob_playback_device_seek (ob_device *player, const uint64_t timestamp, ob_error **error)
Set the playback to a specified time point of the played data.
OB_EXPORT void ob_playback_device_set_playback_rate (ob_device *player, const float rate, ob_error **error)
Set the playback to a specified time point of the played data.
OB_EXPORT ob_playback_status ob_playback_device_get_current_playback_status (ob_device *player, ob_error **error)
Get the current playback status of the played data.
OB_EXPORT void ob_playback_device_set_playback_status_changed_callback (ob_device *player, ob_playback_status_changed_callback callback, void *user_data, ob_error **error)
Set a callback function to receive playback status updates.
OB_EXPORT uint64_t ob_playback_device_get_position (ob_device *player, ob_error **error)
Get the current playback position of the played data.
OB_EXPORT uint64_t ob_playback_device_get_duration (ob_device *player, ob_error **error)
Get the duration of the played data.
Function Documentation
ob_create_record_device()
OB_EXPORT ob_record_device * ob_create_record_device (ob_device * device, const char * file_path, bool compression_enabled, ob_error ** error)
Create a recording device for the specified device with a specified file path and compression enabled.
Parameters
[in] device The device to record.
[in] file_path The file path to record to.
[in] compression_enabled Whether to enable compression for the recording.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
A pointer to the newly created recording device, or NULL if an error occurred.
Referenced by ob::RecordDevice::RecordDevice().
ob_delete_record_device()
OB_EXPORT void ob_delete_record_device (ob_record_device * recorder, ob_error ** error)
Delete a recording device.
Parameters
[in] recorder The recording device to delete.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::RecordDevice::~RecordDevice().
ob_record_device_pause()
OB_EXPORT void ob_record_device_pause (ob_record_device * recorder, ob_error ** error)
Pause recording on the specified recording device.
Parameters
[in] recorder The recording device to pause.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::RecordDevice::pause().
ob_record_device_resume()
OB_EXPORT void ob_record_device_resume (ob_record_device * recorder, ob_error ** error)
Resume recording on the specified recording device.
Parameters
[in] recorder The recording device to resume.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::RecordDevice::resume().
ob_create_playback_device()
OB_EXPORT ob_device * ob_create_playback_device (const char * file_path, ob_error ** error)
Create a playback device for the specified file path.
Parameters
[in] file_path The file path to playback from.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
A pointer to the newly created playback device, or NULL if an error occurred.
Referenced by ob::PlaybackDevice::PlaybackDevice().
ob_playback_device_pause()
OB_EXPORT void ob_playback_device_pause (ob_device * player, ob_error ** error)
Pause playback on the specified playback device.
Parameters
[in] player The playback device to pause.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::PlaybackDevice::pause().
ob_playback_device_resume()
OB_EXPORT void ob_playback_device_resume (ob_device * player, ob_error ** error)
Resume playback on the specified playback device.
Parameters
[in] player The playback device to resume.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::PlaybackDevice::resume().
ob_playback_device_seek()
OB_EXPORT void ob_playback_device_seek (ob_device * player, const uint64_t timestamp, ob_error ** error)
Set the playback to a specified time point of the played data.
Parameters
[in] player The playback device to set the position for.
[in] timestamp The position to set the playback to, in milliseconds.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::PlaybackDevice::seek().
ob_playback_device_set_playback_rate()
OB_EXPORT void ob_playback_device_set_playback_rate (ob_device * player, const float rate, ob_error ** error)
Set the playback to a specified time point of the played data.
Parameters
[in] player The playback device to set the position for.
[in] rate The playback rate to set.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::PlaybackDevice::setPlaybackRate().
ob_playback_device_get_current_playback_status()
OB_EXPORT ob_playback_status ob_playback_device_get_current_playback_status (ob_device * player, ob_error ** error)
Get the current playback status of the played data.
Parameters
[in] player The playback device to get the status for.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The current playback status of the played data.
Referenced by ob::PlaybackDevice::getPlaybackStatus().
ob_playback_device_set_playback_status_changed_callback()
OB_EXPORT void ob_playback_device_set_playback_status_changed_callback (ob_device * player, ob_playback_status_changed_callback callback, void * user_data, ob_error ** error)
Set a callback function to receive playback status updates.
Parameters
[in] player The playback device to set the callback for.
[in] callback The callback function to receive playback status updates.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::PlaybackDevice::setPlaybackStatusChangeCallback().
ob_playback_device_get_position()
OB_EXPORT uint64_t ob_playback_device_get_position (ob_device * player, ob_error ** error)
Get the current playback position of the played data.
Parameters
[in] player The playback device to get the position for.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The current playback position of the played data, in milliseconds.
Referenced by ob::PlaybackDevice::getPosition().
ob_playback_device_get_duration()
OB_EXPORT uint64_t ob_playback_device_get_duration (ob_device * player, ob_error ** error)
Get the duration of the played data.
Parameters
[in] player The playback device to get the duration for.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The duration of the played data, in milliseconds.
Referenced by ob::PlaybackDevice::getDuration().