OrbbecSDK: E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/h/Sensor.h File Reference
Sensor.h File Reference
Defines types related to sensors, used for obtaining stream configurations, opening and closing streams, and setting and getting sensor properties.
#include "ObTypes.h"
Macros
#define ob_sensor_list_get_sensor_count ob_sensor_list_get_count
#define ob_sensor_get_recommended_filter_list ob_sensor_create_recommended_filter_list
Functions
OB_EXPORT ob_sensor_type ob_sensor_get_type (const ob_sensor *sensor, ob_error **error)
Get the type of the sensor.
OB_EXPORT ob_stream_profile_list * ob_sensor_get_stream_profile_list (const ob_sensor *sensor, ob_error **error)
Get a list of all supported stream profiles.
OB_EXPORT void ob_sensor_start (ob_sensor *sensor, const ob_stream_profile *profile, ob_frame_callback callback, void *user_data, ob_error **error)
Open the current sensor and set the callback data frame.
OB_EXPORT void ob_sensor_stop (ob_sensor *sensor, ob_error **error)
Stop the sensor stream.
OB_EXPORT void ob_sensor_switch_profile (ob_sensor *sensor, ob_stream_profile *profile, ob_error **error)
Switch resolutions.
OB_EXPORT void ob_delete_sensor (ob_sensor *sensor, ob_error **error)
Delete a sensor object.
OB_EXPORT ob_filter_list * ob_sensor_create_recommended_filter_list (const ob_sensor *sensor, ob_error **error)
Create a list of recommended filters for the specified sensor.
OB_EXPORT uint32_t ob_sensor_list_get_count (const ob_sensor_list *sensor_list, ob_error **error)
Get the number of sensors in the sensor list.
OB_EXPORT ob_sensor_type ob_sensor_list_get_sensor_type (const ob_sensor_list *sensor_list, uint32_t index, ob_error **error)
Get the sensor type.
OB_EXPORT ob_sensor * ob_sensor_list_get_sensor_by_type (const ob_sensor_list *sensor_list, ob_sensor_type sensorType, ob_error **error)
Get a sensor by sensor type.
OB_EXPORT ob_sensor * ob_sensor_list_get_sensor (const ob_sensor_list *sensor_list, uint32_t index, ob_error **error)
Get a sensor by index number.
OB_EXPORT void ob_delete_sensor_list (ob_sensor_list *sensor_list, ob_error **error)
Delete a list of sensor objects.
Detailed Description
Defines types related to sensors, used for obtaining stream configurations, opening and closing streams, and setting and getting sensor properties.
Definition in file Sensor.h.
Macro Definition Documentation
ob_sensor_list_get_sensor_count
#define ob_sensor_list_get_sensor_count ob_sensor_list_get_count
Definition at line 127 of file Sensor.h.
ob_sensor_get_recommended_filter_list
#define ob_sensor_get_recommended_filter_list ob_sensor_create_recommended_filter_list
Definition at line 128 of file Sensor.h.
Function Documentation
ob_sensor_get_type()
OB_EXPORT ob_sensor_type ob_sensor_get_type (const ob_sensor * sensor, ob_error ** error)
Get the type of the sensor.
Parameters
[in] sensor The sensor object.
[out] error Logs error messages.
Returns
The sensor type.
Referenced by ob::Sensor::getType().
ob_sensor_get_stream_profile_list()
OB_EXPORT ob_stream_profile_list * ob_sensor_get_stream_profile_list (const ob_sensor * sensor, ob_error ** error)
Get a list of all supported stream profiles.
Parameters
[in] sensor The sensor object.
[out] error Logs error messages.
Returns
A list of stream profiles.
Referenced by ob::Sensor::getStreamProfileList().
ob_sensor_start()
OB_EXPORT void ob_sensor_start (ob_sensor * sensor, const ob_stream_profile * profile, ob_frame_callback callback, void * user_data, ob_error ** error)
Open the current sensor and set the callback data frame.
Parameters
[in] sensor The sensor object.
[in] profile The stream configuration information.
[in] callback The callback function triggered when frame data arrives.
[in] user_data Any user data to pass in and get from the callback.
[out] error Logs error messages.
Referenced by ob::Sensor::start().
ob_sensor_stop()
OB_EXPORT void ob_sensor_stop (ob_sensor * sensor, ob_error ** error)
Stop the sensor stream.
Parameters
[in] sensor The sensor object.
[out] error Logs error messages.
Referenced by ob::Sensor::stop().
ob_sensor_switch_profile()
OB_EXPORT void ob_sensor_switch_profile (ob_sensor * sensor, ob_stream_profile * profile, ob_error ** error)
Switch resolutions.
Parameters
[in] sensor The sensor object.
[in] profile The stream configuration information.
[out] error Logs error messages.
Referenced by ob::Sensor::switchProfile().
ob_delete_sensor()
OB_EXPORT void ob_delete_sensor (ob_sensor * sensor, ob_error ** error)
Delete a sensor object.
Parameters
[in] sensor The sensor object to delete.
[out] error Logs error messages.
Referenced by ob::Sensor::operator=(), and ob::Sensor::~Sensor().
ob_sensor_create_recommended_filter_list()
OB_EXPORT ob_filter_list * ob_sensor_create_recommended_filter_list (const ob_sensor * sensor, ob_error ** error)
Create a list of recommended filters for the specified sensor.
Parameters
[in] sensor The ob_sensor object.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_filter_list
Referenced by ob::Sensor::createRecommendedFilters().
ob_sensor_list_get_count()
OB_EXPORT uint32_t ob_sensor_list_get_count (const ob_sensor_list * sensor_list, ob_error ** error)
Get the number of sensors in the sensor list.
Parameters
[in] sensor_list The list of sensor objects.
[out] error Logs error messages.
Returns
The number of sensors in the list.
Referenced by ob::SensorList::getCount().
ob_sensor_list_get_sensor_type()
OB_EXPORT ob_sensor_type ob_sensor_list_get_sensor_type (const ob_sensor_list * sensor_list, uint32_t index, ob_error ** error)
Get the sensor type.
Parameters
[in] sensor_list The list of sensor objects.
[in] index The index of the sensor on the list.
[out] error Logs error messages.
Returns
The sensor type.
Referenced by ob::SensorList::getSensorType().
ob_sensor_list_get_sensor_by_type()
OB_EXPORT ob_sensor * ob_sensor_list_get_sensor_by_type (const ob_sensor_list * sensor_list, ob_sensor_type sensorType, ob_error ** error)
Get a sensor by sensor type.
Parameters
[in] sensor_list The list of sensor objects.
[in] sensorType The sensor type to be obtained.
[out] error Logs error messages.
Returns
The sensor pointer. If the specified type of sensor does not exist, it will return null.
Referenced by ob::SensorList::getSensor().
ob_sensor_list_get_sensor()
OB_EXPORT ob_sensor * ob_sensor_list_get_sensor (const ob_sensor_list * sensor_list, uint32_t index, ob_error ** error)
Get a sensor by index number.
Parameters
[in] sensor_list The list of sensor objects.
[in] index The index of the sensor on the list.
[out] error Logs error messages.
Returns
The sensor object.
Referenced by ob::SensorList::getSensor().
ob_delete_sensor_list()
OB_EXPORT void ob_delete_sensor_list (ob_sensor_list * sensor_list, ob_error ** error)
Delete a list of sensor objects.
Parameters
[in] sensor_list The list of sensor objects to delete.
[out] error Logs error messages.
Referenced by ob::SensorList::~SensorList().