OrbbecSDK: E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/h/StreamProfile.h File Reference
StreamProfile.h File Reference
The stream profile related type is used to get information such as the width, height, frame rate, and format of the stream.
#include "ObTypes.h"
Macros
#define ob_stream_profile_format ob_stream_profile_get_format
#define ob_stream_profile_type ob_stream_profile_get_type
#define ob_video_stream_profile_fps ob_video_stream_profile_get_fps
#define ob_video_stream_profile_width ob_video_stream_profile_get_width
#define ob_video_stream_profile_height ob_video_stream_profile_get_height
#define ob_accel_stream_profile_full_scale_range ob_accel_stream_profile_get_full_scale_range
#define ob_accel_stream_profile_sample_rate ob_accel_stream_profile_get_sample_rate
#define ob_gyro_stream_profile_full_scale_range ob_gyro_stream_profile_get_full_scale_range
#define ob_gyro_stream_profile_sample_rate ob_gyro_stream_profile_get_sample_rate
#define ob_stream_profile_list_count ob_stream_profile_list_get_count
Functions
OB_EXPORT ob_stream_profile * ob_create_stream_profile (ob_stream_type type, ob_format format, ob_error **error)
Create a stream profile object.
OB_EXPORT ob_stream_profile * ob_create_video_stream_profile (ob_stream_type type, ob_format format, uint32_t width, uint32_t height, uint32_t fps, ob_error **error)
Create a video stream profile object.
OB_EXPORT ob_stream_profile * ob_create_accel_stream_profile (ob_accel_full_scale_range full_scale_range, ob_accel_sample_rate sample_rate, ob_error **error)
Create a accel stream profile object.
OB_EXPORT ob_stream_profile * ob_create_gyro_stream_profile (ob_gyro_full_scale_range full_scale_range, ob_gyro_sample_rate sample_rate, ob_error **error)
Create a gyro stream profile object.
OB_EXPORT ob_stream_profile * ob_create_stream_profile_from_other_stream_profile (const ob_stream_profile *srcProfile, ob_error **error)
Copy the stream profile object from an other stream profile object.
OB_EXPORT ob_stream_profile * ob_create_stream_profile_with_new_format (const ob_stream_profile *profile, ob_format new_format, ob_error **error)
Copy the stream profile object with a new format object.
OB_EXPORT void ob_delete_stream_profile (const ob_stream_profile *profile, ob_error **error)
Delete the stream configuration.
OB_EXPORT ob_format ob_stream_profile_get_format (const ob_stream_profile *profile, ob_error **error)
Get stream profile format.
OB_EXPORT void ob_stream_profile_set_format (ob_stream_profile *profile, ob_format format, ob_error **error)
Set stream profile format.
OB_EXPORT ob_stream_type ob_stream_profile_get_type (const ob_stream_profile *profile, ob_error **error)
Get stream profile type.
OB_EXPORT void ob_stream_profile_set_type (const ob_stream_profile *profile, ob_stream_type type, ob_error **error)
Set stream profile type.
OB_EXPORT ob_extrinsic ob_stream_profile_get_extrinsic_to (const ob_stream_profile *source, ob_stream_profile *target, ob_error **error)
Get the extrinsic for source stream to target stream.
OB_EXPORT void ob_stream_profile_set_extrinsic_to (ob_stream_profile *source, const ob_stream_profile *target, ob_extrinsic extrinsic, ob_error **error)
Set the extrinsic for source stream to target stream.
OB_EXPORT void ob_stream_profile_set_extrinsic_to_type (ob_stream_profile *source, const ob_stream_type type, ob_extrinsic extrinsic, ob_error **error)
Set the extrinsic for source stream to target stream type.
OB_EXPORT uint32_t ob_video_stream_profile_get_fps (const ob_stream_profile *profile, ob_error **error)
Get the frame rate of the video stream.
OB_EXPORT uint32_t ob_video_stream_profile_get_width (const ob_stream_profile *profile, ob_error **error)
Get the width of the video stream.
OB_EXPORT void ob_video_stream_profile_set_width (ob_stream_profile *profile, uint32_t width, ob_error **error)
Set the width of the video stream.
OB_EXPORT uint32_t ob_video_stream_profile_get_height (const ob_stream_profile *profile, ob_error **error)
Get the height of the video stream.
OB_EXPORT void ob_video_stream_profile_set_height (ob_stream_profile *profile, uint32_t height, ob_error **error)
Set the height of the video stream.
OB_EXPORT ob_camera_intrinsic ob_video_stream_profile_get_intrinsic (const ob_stream_profile *profile, ob_error **error)
Get the intrinsic of the video stream profile.
OB_EXPORT void ob_video_stream_profile_set_intrinsic (ob_stream_profile *profile, ob_camera_intrinsic intrinsic, ob_error **error)
Set the intrinsic of the video stream profile.
OB_EXPORT ob_camera_distortion ob_video_stream_profile_get_distortion (const ob_stream_profile *profile, ob_error **error)
Get the distortion of the video stream profile.
OB_EXPORT void ob_video_stream_profile_set_distortion (ob_stream_profile *profile, ob_camera_distortion distortion, ob_error **error)
Set the distortion of the video stream profile.
OB_EXPORT ob_disparity_param ob_disparity_based_stream_profile_get_disparity_param (const ob_stream_profile *profile, ob_error **error)
Get the process param of the disparity stream.
OB_EXPORT void ob_disparity_based_stream_profile_set_disparity_param (ob_stream_profile *profile, ob_disparity_param param, ob_error **error)
Set the disparity process param of the disparity stream.
OB_EXPORT ob_accel_full_scale_range ob_accel_stream_profile_get_full_scale_range (const ob_stream_profile *profile, ob_error **error)
Get the full-scale range of the accelerometer stream.
OB_EXPORT ob_accel_sample_rate ob_accel_stream_profile_get_sample_rate (const ob_stream_profile *profile, ob_error **error)
Get the sampling frequency of the accelerometer frame.
OB_EXPORT ob_accel_intrinsic ob_accel_stream_profile_get_intrinsic (const ob_stream_profile *profile, ob_error **error)
Get the intrinsic of the accelerometer stream.
OB_EXPORT void ob_accel_stream_profile_set_intrinsic (ob_stream_profile *profile, ob_accel_intrinsic intrinsic, ob_error **error)
Set the intrinsic of the accelerometer stream.
OB_EXPORT ob_gyro_full_scale_range ob_gyro_stream_profile_get_full_scale_range (const ob_stream_profile *profile, ob_error **error)
Get the full-scale range of the gyroscope stream.
OB_EXPORT ob_gyro_sample_rate ob_gyro_stream_profile_get_sample_rate (const ob_stream_profile *profile, ob_error **error)
Get the sampling frequency of the gyroscope stream.
OB_EXPORT ob_gyro_intrinsic ob_gyro_stream_get_intrinsic (const ob_stream_profile *profile, ob_error **error)
Get the intrinsic of the gyroscope stream.
OB_EXPORT void ob_gyro_stream_set_intrinsic (ob_stream_profile *profile, ob_gyro_intrinsic intrinsic, ob_error **error)
Set the intrinsic of the gyroscope stream.
OB_EXPORT uint32_t ob_stream_profile_list_get_count (const ob_stream_profile_list *profile_list, ob_error **error)
Get the number of StreamProfile lists.
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_profile (const ob_stream_profile_list *profile_list, int index, ob_error **error)
Get the corresponding StreamProfile by subscripting.
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_video_stream_profile (const ob_stream_profile_list *profile_list, int width, int height, ob_format format, int fps, ob_error **error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_accel_stream_profile (const ob_stream_profile_list *profile_list, ob_accel_full_scale_range full_scale_range, ob_accel_sample_rate sample_rate, ob_error **error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_gyro_stream_profile (const ob_stream_profile_list *profile_list, ob_gyro_full_scale_range full_scale_range, ob_gyro_sample_rate sample_rate, ob_error **error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
OB_EXPORT void ob_delete_stream_profile_list (const ob_stream_profile_list *profile_list, ob_error **error)
Delete the stream profile list.
Detailed Description
The stream profile related type is used to get information such as the width, height, frame rate, and format of the stream.
Definition in file StreamProfile.h.
Macro Definition Documentation
ob_stream_profile_format
#define ob_stream_profile_format ob_stream_profile_get_format
Definition at line 404 of file StreamProfile.h.
ob_stream_profile_type
#define ob_stream_profile_type ob_stream_profile_get_type
Definition at line 405 of file StreamProfile.h.
ob_video_stream_profile_fps
#define ob_video_stream_profile_fps ob_video_stream_profile_get_fps
Definition at line 406 of file StreamProfile.h.
ob_video_stream_profile_width
#define ob_video_stream_profile_width ob_video_stream_profile_get_width
Definition at line 407 of file StreamProfile.h.
ob_video_stream_profile_height
#define ob_video_stream_profile_height ob_video_stream_profile_get_height
Definition at line 408 of file StreamProfile.h.
ob_accel_stream_profile_full_scale_range
#define ob_accel_stream_profile_full_scale_range ob_accel_stream_profile_get_full_scale_range
Definition at line 409 of file StreamProfile.h.
ob_accel_stream_profile_sample_rate
#define ob_accel_stream_profile_sample_rate ob_accel_stream_profile_get_sample_rate
Definition at line 410 of file StreamProfile.h.
ob_gyro_stream_profile_full_scale_range
#define ob_gyro_stream_profile_full_scale_range ob_gyro_stream_profile_get_full_scale_range
Definition at line 411 of file StreamProfile.h.
ob_gyro_stream_profile_sample_rate
#define ob_gyro_stream_profile_sample_rate ob_gyro_stream_profile_get_sample_rate
Definition at line 412 of file StreamProfile.h.
ob_stream_profile_list_count
#define ob_stream_profile_list_count ob_stream_profile_list_get_count
Definition at line 413 of file StreamProfile.h.
Function Documentation
ob_create_stream_profile()
OB_EXPORT ob_stream_profile * ob_create_stream_profile (ob_stream_type type, ob_format format, ob_error ** error)
Create a stream profile object.
Parameters
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the stream profile object
ob_create_video_stream_profile()
OB_EXPORT ob_stream_profile * ob_create_video_stream_profile (ob_stream_type type, ob_format format, uint32_t width, uint32_t height, uint32_t fps, ob_error ** error)
Create a video stream profile object.
Parameters
[in] type Stream type
[in] format Stream format
[in] width Stream width
[in] height Stream height
[in] fps Stream frame rate
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the video stream profile object
ob_create_accel_stream_profile()
OB_EXPORT ob_stream_profile * ob_create_accel_stream_profile (ob_accel_full_scale_range full_scale_range, ob_accel_sample_rate sample_rate, ob_error ** error)
Create a accel stream profile object.
Parameters
[in] full_scale_range Accel full scale range
[in] sample_rate Accel sample rate
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the accel stream profile object
ob_create_gyro_stream_profile()
OB_EXPORT ob_stream_profile * ob_create_gyro_stream_profile (ob_gyro_full_scale_range full_scale_range, ob_gyro_sample_rate sample_rate, ob_error ** error)
Create a gyro stream profile object.
Parameters
[in] full_scale_range Gyro full scale range
[in] sample_rate Gyro sample rate
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the accel stream profile object
ob_create_stream_profile_from_other_stream_profile()
OB_EXPORT ob_stream_profile * ob_create_stream_profile_from_other_stream_profile (const ob_stream_profile * srcProfile, ob_error ** error)
Copy the stream profile object from an other stream profile object.
Parameters
[in] srcProfile Source stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the new stream profile object
ob_create_stream_profile_with_new_format()
OB_EXPORT ob_stream_profile * ob_create_stream_profile_with_new_format (const ob_stream_profile * profile, ob_format new_format, ob_error ** error)
Copy the stream profile object with a new format object.
Parameters
[in] profile Stream profile object
[in] new_format New format
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_profile* return the new stream profile object with the new format
ob_delete_stream_profile()
OB_EXPORT void ob_delete_stream_profile (const ob_stream_profile * profile, ob_error ** error)
Delete the stream configuration.
Parameters
[in] profile Stream profile object .
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::StreamProfile::operator=(), and ob::StreamProfile::~StreamProfile().
ob_stream_profile_get_format()
OB_EXPORT ob_format ob_stream_profile_get_format (const ob_stream_profile * profile, ob_error ** error)
Get stream profile format.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_format return the format of the stream
Referenced by ob::StreamProfile::getFormat().
ob_stream_profile_set_format()
OB_EXPORT void ob_stream_profile_set_format (ob_stream_profile * profile, ob_format format, ob_error ** error)
Set stream profile format.
Parameters
[in] profile Stream profile object
[in] format The format of the stream
[out] error Pointer to an error object that will be set if an error occurs.
ob_stream_profile_get_type()
OB_EXPORT ob_stream_type ob_stream_profile_get_type (const ob_stream_profile * profile, ob_error ** error)
Get stream profile type.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_stream_type stream type
Referenced by ob::StreamProfileFactory::create(), and ob::StreamProfile::getType().
ob_stream_profile_set_type()
OB_EXPORT void ob_stream_profile_set_type (const ob_stream_profile * profile, ob_stream_type type, ob_error ** error)
Set stream profile type.
Parameters
[in] profile Stream profile object
[in] type The type of the stream
[out] error Pointer to an error object that will be set if an error occurs.
ob_stream_profile_get_extrinsic_to()
OB_EXPORT ob_extrinsic ob_stream_profile_get_extrinsic_to (const ob_stream_profile * source, ob_stream_profile * target, ob_error ** error)
Get the extrinsic for source stream to target stream.
Parameters
[in] source Source stream profile
[in] target Target stream profile
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_extrinsic The extrinsic
Referenced by ob::StreamProfile::getExtrinsicTo().
ob_stream_profile_set_extrinsic_to()
OB_EXPORT void ob_stream_profile_set_extrinsic_to (ob_stream_profile * source, const ob_stream_profile * target, ob_extrinsic extrinsic, ob_error ** error)
Set the extrinsic for source stream to target stream.
Parameters
[in] source Stream profile object
[in] target Target stream type
[in] extrinsic The extrinsic
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::StreamProfile::bindExtrinsicTo().
ob_stream_profile_set_extrinsic_to_type()
OB_EXPORT void ob_stream_profile_set_extrinsic_to_type (ob_stream_profile * source, const ob_stream_type type, ob_extrinsic extrinsic, ob_error ** error)
Set the extrinsic for source stream to target stream type.
Parameters
[in] source Source stream profile
[in] type Target stream type
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_extrinsic The extrinsic
Referenced by ob::StreamProfile::bindExtrinsicTo().
ob_video_stream_profile_get_fps()
OB_EXPORT uint32_t ob_video_stream_profile_get_fps (const ob_stream_profile * profile, ob_error ** error)
Get the frame rate of the video stream.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
uint32_t return the frame rate of the stream
Referenced by ob::VideoStreamProfile::getFps().
ob_video_stream_profile_get_width()
OB_EXPORT uint32_t ob_video_stream_profile_get_width (const ob_stream_profile * profile, ob_error ** error)
Get the width of the video stream.
Parameters
[in] profile Stream profile object , If the profile is not a video stream configuration, an error will be returned
[out] error Pointer to an error object that will be set if an error occurs.
Returns
uint32_t return the width of the stream
Referenced by ob::VideoStreamProfile::getWidth().
ob_video_stream_profile_set_width()
OB_EXPORT void ob_video_stream_profile_set_width (ob_stream_profile * profile, uint32_t width, ob_error ** error)
Set the width of the video stream.
Parameters
[in] profile Stream profile object , If the profile is not a video stream configuration, an error will be returned
[in] width The width of the stream
[out] error Pointer to an error object that will be set if an error occurs.
ob_video_stream_profile_get_height()
OB_EXPORT uint32_t ob_video_stream_profile_get_height (const ob_stream_profile * profile, ob_error ** error)
Get the height of the video stream.
Parameters
[in] profile Stream profile object , If the profile is not a video stream configuration, an error will be returned
[out] error Pointer to an error object that will be set if an error occurs.
Returns
uint32_t return the height of the stream
Referenced by ob::VideoStreamProfile::getHeight().
ob_video_stream_profile_set_height()
OB_EXPORT void ob_video_stream_profile_set_height (ob_stream_profile * profile, uint32_t height, ob_error ** error)
Set the height of the video stream.
Parameters
[in] profile Stream profile object , If the profile is not a video stream configuration, an error will be returned
[in] height The height of the stream
[out] error Pointer to an error object that will be set if an error occurs.
ob_video_stream_profile_get_intrinsic()
OB_EXPORT ob_camera_intrinsic ob_video_stream_profile_get_intrinsic (const ob_stream_profile * profile, ob_error ** error)
Get the intrinsic of the video stream profile.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_camera_intrinsic Return the intrinsic of the stream
Referenced by ob::VideoStreamProfile::getIntrinsic().
ob_video_stream_profile_set_intrinsic()
OB_EXPORT void ob_video_stream_profile_set_intrinsic (ob_stream_profile * profile, ob_camera_intrinsic intrinsic, ob_error ** error)
Set the intrinsic of the video stream profile.
Parameters
[in] profile Stream profile object
[in] intrinsic The intrinsic of the stream
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::VideoStreamProfile::setIntrinsic().
ob_video_stream_profile_get_distortion()
OB_EXPORT ob_camera_distortion ob_video_stream_profile_get_distortion (const ob_stream_profile * profile, ob_error ** error)
Get the distortion of the video stream profile.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_camera_distortion Return the distortion of the stream
Referenced by ob::VideoStreamProfile::getDistortion().
ob_video_stream_profile_set_distortion()
OB_EXPORT void ob_video_stream_profile_set_distortion (ob_stream_profile * profile, ob_camera_distortion distortion, ob_error ** error)
Set the distortion of the video stream profile.
Parameters
[in] profile Stream profile object
[in] distortion The distortion of the stream
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::VideoStreamProfile::setDistortion().
ob_disparity_based_stream_profile_get_disparity_param()
OB_EXPORT ob_disparity_param ob_disparity_based_stream_profile_get_disparity_param (const ob_stream_profile * profile, ob_error ** error)
Get the process param of the disparity stream.
Parameters
[in] profile Stream profile object
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_disparity_param Return the disparity process param of the stream
ob_disparity_based_stream_profile_set_disparity_param()
OB_EXPORT void ob_disparity_based_stream_profile_set_disparity_param (ob_stream_profile * profile, ob_disparity_param param, ob_error ** error)
Set the disparity process param of the disparity stream.
Parameters
[in] profile Stream profile object. If the profile is not for the disparity stream, an error will be returned.
[in] param The disparity process param of the disparity stream.
[out] error Pointer to an error object that will be set if an error occurs.
ob_accel_stream_profile_get_full_scale_range()
OB_EXPORT ob_accel_full_scale_range ob_accel_stream_profile_get_full_scale_range (const ob_stream_profile * profile, ob_error ** error)
Get the full-scale range of the accelerometer stream.
Parameters
[in] profile Stream profile object. If the profile is not for the accelerometer stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The full-scale range of the accelerometer stream.
Referenced by ob::AccelStreamProfile::getFullScaleRange().
ob_accel_stream_profile_get_sample_rate()
OB_EXPORT ob_accel_sample_rate ob_accel_stream_profile_get_sample_rate (const ob_stream_profile * profile, ob_error ** error)
Get the sampling frequency of the accelerometer frame.
Parameters
[in] profile Stream profile object. If the profile is not for the accelerometer stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The sampling frequency of the accelerometer frame.
Referenced by ob::AccelStreamProfile::getSampleRate().
ob_accel_stream_profile_get_intrinsic()
OB_EXPORT ob_accel_intrinsic ob_accel_stream_profile_get_intrinsic (const ob_stream_profile * profile, ob_error ** error)
Get the intrinsic of the accelerometer stream.
Parameters
[in] profile Stream profile object. If the profile is not for the accelerometer stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_accel_intrinsic Return the intrinsic of the accelerometer stream.
Referenced by ob::AccelStreamProfile::getIntrinsic().
ob_accel_stream_profile_set_intrinsic()
OB_EXPORT void ob_accel_stream_profile_set_intrinsic (ob_stream_profile * profile, ob_accel_intrinsic intrinsic, ob_error ** error)
Set the intrinsic of the accelerometer stream.
Parameters
[in] profile Stream profile object. If the profile is not for the accelerometer stream, an error will be returned.
[in] intrinsic The intrinsic of the accelerometer stream.
[out] error Pointer to an error object that will be set if an error occurs.
ob_gyro_stream_profile_get_full_scale_range()
OB_EXPORT ob_gyro_full_scale_range ob_gyro_stream_profile_get_full_scale_range (const ob_stream_profile * profile, ob_error ** error)
Get the full-scale range of the gyroscope stream.
Parameters
[in] profile Stream profile object. If the profile is not for the gyroscope stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The full-scale range of the gyroscope stream.
Referenced by ob::GyroStreamProfile::getFullScaleRange().
ob_gyro_stream_profile_get_sample_rate()
OB_EXPORT ob_gyro_sample_rate ob_gyro_stream_profile_get_sample_rate (const ob_stream_profile * profile, ob_error ** error)
Get the sampling frequency of the gyroscope stream.
Parameters
[in] profile Stream profile object. If the profile is not for the gyroscope stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The sampling frequency of the gyroscope stream.
Referenced by ob::GyroStreamProfile::getSampleRate().
ob_gyro_stream_get_intrinsic()
OB_EXPORT ob_gyro_intrinsic ob_gyro_stream_get_intrinsic (const ob_stream_profile * profile, ob_error ** error)
Get the intrinsic of the gyroscope stream.
Parameters
[in] profile Stream profile object. If the profile is not for the gyroscope stream, an error will be returned.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
ob_gyro_intrinsic Return the intrinsic of the gyroscope stream.
Referenced by ob::GyroStreamProfile::getIntrinsic().
ob_gyro_stream_set_intrinsic()
OB_EXPORT void ob_gyro_stream_set_intrinsic (ob_stream_profile * profile, ob_gyro_intrinsic intrinsic, ob_error ** error)
Set the intrinsic of the gyroscope stream.
Parameters
[in] profile Stream profile object. If the profile is not for the gyroscope stream, an error will be returned.
[in] intrinsic The intrinsic of the gyroscope stream.
[out] error Pointer to an error object that will be set if an error occurs.
ob_stream_profile_list_get_count()
OB_EXPORT uint32_t ob_stream_profile_list_get_count (const ob_stream_profile_list * profile_list, ob_error ** error)
Get the number of StreamProfile lists.
Parameters
[in] profile_list StreamProfile list.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The number of StreamProfile lists.
Referenced by ob::StreamProfileList::getCount().
ob_stream_profile_list_get_profile()
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_profile (const ob_stream_profile_list * profile_list, int index, ob_error ** error)
Get the corresponding StreamProfile by subscripting.
Attention
The stream profile returned by this function should be deleted by calling ob_delete_stream_profile() when it is no longer needed.
Parameters
[in] profile_list StreamProfile lists.
[in] index Index.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The matching profile.
Referenced by ob::StreamProfileList::getProfile().
ob_stream_profile_list_get_video_stream_profile()
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_video_stream_profile (const ob_stream_profile_list * profile_list, int width, int height, ob_format format, int fps, ob_error ** error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
Attention
The stream profile returned by this function should be deleted by calling ob_delete_stream_profile() when it is no longer needed.
Parameters
[in] profile_list Resolution list.
[in] width Width. If you don't need to add matching conditions, you can pass OB_WIDTH_ANY.
[in] height Height. If you don't need to add matching conditions, you can pass OB_HEIGHT_ANY.
[in] format Format. If you don't need to add matching conditions, you can pass OB_FORMAT_ANY.
[in] fps Frame rate. If you don't need to add matching conditions, you can pass OB_FPS_ANY.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The matching profile.
Referenced by ob::StreamProfileList::getVideoStreamProfile().
ob_stream_profile_list_get_accel_stream_profile()
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_accel_stream_profile (const ob_stream_profile_list * profile_list, ob_accel_full_scale_range full_scale_range, ob_accel_sample_rate sample_rate, ob_error ** error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
Attention
The stream profile returned by this function should be deleted by calling ob_delete_stream_profile() when it is no longer needed.
Parameters
[in] profile_list Resolution list.
[in] full_scale_range Full-scale range. If you don't need to add matching conditions, you can pass 0.
[in] sample_rate Sample rate. If you don't need to add matching conditions, you can pass 0.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The matching profile.
Referenced by ob::StreamProfileList::getAccelStreamProfile().
ob_stream_profile_list_get_gyro_stream_profile()
OB_EXPORT ob_stream_profile * ob_stream_profile_list_get_gyro_stream_profile (const ob_stream_profile_list * profile_list, ob_gyro_full_scale_range full_scale_range, ob_gyro_sample_rate sample_rate, ob_error ** error)
Match the corresponding ob_stream_profile through the passed parameters. If there are multiple matches, the first one in the list will be returned by default. If no matched profile is found, an error will be returned.
Attention
The stream profile returned by this function should be deleted by calling ob_delete_stream_profile() when it is no longer needed.
Parameters
[in] profile_list Resolution list.
[in] full_scale_range Full-scale range. If you don't need to add matching conditions, you can pass 0.
[in] sample_rate Sample rate. If you don't need to add matching conditions, you can pass 0.
[out] error Pointer to an error object that will be set if an error occurs.
Returns
The matching profile.
Referenced by ob::StreamProfileList::getGyroStreamProfile().
ob_delete_stream_profile_list()
OB_EXPORT void ob_delete_stream_profile_list (const ob_stream_profile_list * profile_list, ob_error ** error)
Delete the stream profile list.
Parameters
[in] profile_list Stream configuration list.
[out] error Pointer to an error object that will be set if an error occurs.
Referenced by ob::StreamProfileList::~StreamProfileList().