OrbbecSDK: C:/Users/hzcyf/Projects/openorbbecsdkgroup/OpenOrbbecSDK/include/libobsensor/h/TypeHelper.h File Reference
TypeHelper.h File Reference
#include "ObTypes.h"
Functions
OB_EXPORT const char * ob_format_type_to_string (OBFormat type)
Convert OBFormat to " char* " type and then return.
OB_EXPORT const char * ob_frame_type_to_string (OBFrameType type)
Convert OBFrameType to " char* " type and then return.
OB_EXPORT const char * ob_stream_type_to_string (OBStreamType type)
Convert OBStreamType to " char* " type and then return.
OB_EXPORT const char * ob_sensor_type_to_string (OBSensorType type)
Convert OBSensorType to " char* " type and then return.
OB_EXPORT const char * ob_imu_rate_type_to_string (OBIMUSampleRate type)
Convert OBIMUSampleRate to " char* " type and then return.
OB_EXPORT const char * ob_gyro_range_type_to_string (OBGyroFullScaleRange type)
Convert OBGyroFullScaleRange to " char* " type and then return.
OB_EXPORT const char * ob_accel_range_type_to_string (OBAccelFullScaleRange type)
Convert OBAccelFullScaleRange to " char* " type and then return.
OB_EXPORT const char * ob_meta_data_type_to_string (OBFrameMetadataType type)
Convert OBFrameMetadataType to " char* " type and then return.
OB_EXPORT OBStreamType ob_sensor_type_to_stream_type (OBSensorType type)
Convert OBStreamType to OBSensorType.
OB_EXPORT const char * ob_format_to_string (OBFormat format)
Convert OBFormat to " char* " type and then return.
Function Documentation
ob_format_type_to_string()
OB_EXPORT const char * ob_format_type_to_string (OBFormat type)
Convert OBFormat to " char* " type and then return.
Parameters
[in] type OBFormat type.
Returns
OBFormat of "char*" type.
Referenced by ob::TypeHelper::convertOBFormatTypeToString().
ob_frame_type_to_string()
OB_EXPORT const char * ob_frame_type_to_string (OBFrameType type)
Convert OBFrameType to " char* " type and then return.
Parameters
[in] type OBFrameType type.
Returns
OBFrameType of "char*" type.
Referenced by ob::TypeHelper::convertOBFrameTypeToString().
ob_stream_type_to_string()
OB_EXPORT const char * ob_stream_type_to_string (OBStreamType type)
Convert OBStreamType to " char* " type and then return.
Parameters
[in] type OBStreamType type.
Returns
OBStreamType of "char*" type.
Referenced by ob::TypeHelper::convertOBStreamTypeToString().
ob_sensor_type_to_string()
OB_EXPORT const char * ob_sensor_type_to_string (OBSensorType type)
Convert OBSensorType to " char* " type and then return.
Parameters
[in] type OBSensorType type.
Returns
OBSensorType of "char*" type.
Referenced by ob::TypeHelper::convertOBSensorTypeToString().
ob_imu_rate_type_to_string()
OB_EXPORT const char * ob_imu_rate_type_to_string (OBIMUSampleRate type)
Convert OBIMUSampleRate to " char* " type and then return.
Parameters
[in] type OBIMUSampleRate type.
Returns
OBIMUSampleRate of "char*" type.
Referenced by ob::TypeHelper::convertOBIMUSampleRateTypeToString().
ob_gyro_range_type_to_string()
OB_EXPORT const char * ob_gyro_range_type_to_string (OBGyroFullScaleRange type)
Convert OBGyroFullScaleRange to " char* " type and then return.
Parameters
[in] type OBGyroFullScaleRange type.
Returns
OBGyroFullScaleRange of "char*" type.
Referenced by ob::TypeHelper::convertOBGyroFullScaleRangeTypeToString().
ob_accel_range_type_to_string()
OB_EXPORT const char * ob_accel_range_type_to_string (OBAccelFullScaleRange type)
Convert OBAccelFullScaleRange to " char* " type and then return.
Parameters
[in] type OBAccelFullScaleRange type.
Returns
OBAccelFullScaleRange of "char*" type.
Referenced by ob::TypeHelper::convertOBAccelFullScaleRangeTypeToString().
ob_meta_data_type_to_string()
OB_EXPORT const char * ob_meta_data_type_to_string (OBFrameMetadataType type)
Convert OBFrameMetadataType to " char* " type and then return.
Parameters
[in] type OBFrameMetadataType type.
Returns
OBFrameMetadataType of "char*" type.
Referenced by ob::TypeHelper::convertOBFrameMetadataTypeToString().
ob_sensor_type_to_stream_type()
OB_EXPORT OBStreamType ob_sensor_type_to_stream_type (OBSensorType type)
Convert OBStreamType to OBSensorType.
Parameters
[in] type The sensor type to convert.
Returns
OBStreamType The corresponding stream type.
Referenced by ob::TypeHelper::convertSensorTypeToStreamType().
ob_format_to_string()
OB_EXPORT const char * ob_format_to_string (OBFormat format)
Convert OBFormat to " char* " type and then return.
Parameters
format The OBFormat to convert.
Returns
The string.