OrbbecSDK: D:/orbbec/openorbbecsdkgroup/OpenOrbbecSDK/include/libobsensor/h/Version.h File Reference
Version.h File Reference
Functions for retrieving the SDK version number information.
#include "Export.h"
Functions
OB_EXPORT int ob_get_version ()
Get the SDK version number.
OB_EXPORT int ob_get_major_version ()
Get the SDK major version number.
OB_EXPORT int ob_get_minor_version ()
Get the SDK minor version number.
OB_EXPORT int ob_get_patch_version ()
Get the SDK patch version number.
OB_EXPORT const char * ob_get_stage_version ()
Get the SDK stage version.
Detailed Description
Functions for retrieving the SDK version number information.
Definition in file Version.h.
Function Documentation
ob_get_version()
OB_EXPORT int ob_get_version ()
Get the SDK version number.
Returns
int The SDK version number.
Referenced by ob::Version::getVersion().
ob_get_major_version()
OB_EXPORT int ob_get_major_version ()
Get the SDK major version number.
Returns
int The SDK major version number.
Referenced by ob::Version::getMajor().
ob_get_minor_version()
OB_EXPORT int ob_get_minor_version ()
Get the SDK minor version number.
Returns
int The SDK minor version number.
Referenced by ob::Version::getMinor().
ob_get_patch_version()
OB_EXPORT int ob_get_patch_version ()
Get the SDK patch version number.
Returns
int The SDK patch version number.
Referenced by ob::Version::getPatch().
ob_get_stage_version()
OB_EXPORT const char * ob_get_stage_version ()
Get the SDK stage version.
Attention
The returned char* does not need to be freed.
Returns
const char* The SDK stage version.
Referenced by ob::Version::getStageVersion().