OrbbecSDK: ob::AccelStreamProfile Class Reference
ob::AccelStreamProfile Class Reference
Class representing an accelerometer stream profile.
#include <StreamProfile.hpp>
Public Member Functions
AccelStreamProfile (const ob_stream_profile_t *impl)
~AccelStreamProfile () noexcept override=default
OBAccelFullScaleRange getFullScaleRange () const
Return the full scale range.
OBAccelSampleRate getSampleRate () const
Return the sampling frequency.
OBAccelIntrinsic getIntrinsic () const
get the intrinsic parameters of the stream.
OBAccelFullScaleRange fullScaleRange () const
OBAccelSampleRate sampleRate () const
Public Member Functions inherited from ob::StreamProfile
StreamProfile (StreamProfile &streamProfile)=delete
StreamProfile & operator= (StreamProfile &streamProfile)=delete
StreamProfile (StreamProfile &&streamProfile) noexcept
StreamProfile & operator= (StreamProfile &&streamProfile) noexcept
virtual ~StreamProfile () noexcept
const ob_stream_profile * getImpl () const
OBFormat getFormat () const
Get the format of the stream.
OBStreamType getType () const
Get the type of stream.
OBExtrinsic getExtrinsicTo (std::shared_ptr< StreamProfile > target) const
Get the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (std::shared_ptr< StreamProfile > target, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (const OBStreamType &targetStreamType, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream type.
template<typename T>
bool is () const
Check if frame object is compatible with the given type.
template<typename T>
std::shared_ptr< T > as ()
Converts object type to target type.
template<typename T>
std::shared_ptr< const T > as () const
Converts object type to target type (const version).
OBFormat format () const
OBStreamType type () const
Additional Inherited Members
Protected Member Functions inherited from ob::StreamProfile
StreamProfile (const ob_stream_profile_t *impl)
Protected Attributes inherited from ob::StreamProfile
const ob_stream_profile_t * impl_ = nullptr
Detailed Description
Class representing an accelerometer stream profile.
Definition at line 272 of file StreamProfile.hpp.
Constructor & Destructor Documentation
AccelStreamProfile()
ob::AccelStreamProfile::AccelStreamProfile (const ob_stream_profile_t * impl) inline explicit
Definition at line 274 of file StreamProfile.hpp.
~AccelStreamProfile()
ob::AccelStreamProfile::~AccelStreamProfile () override default noexcept
Member Function Documentation
getFullScaleRange()
OBAccelFullScaleRange ob::AccelStreamProfile::getFullScaleRange () const inline
Return the full scale range.
Returns
OBAccelFullScaleRange Return the scale range value.
Definition at line 283 of file StreamProfile.hpp.
Referenced by fullScaleRange(), and getFullScaleRange().
getSampleRate()
OBAccelSampleRate ob::AccelStreamProfile::getSampleRate () const inline
Return the sampling frequency.
Returns
OBAccelFullScaleRange Return the sampling frequency.
Definition at line 295 of file StreamProfile.hpp.
Referenced by sampleRate().
getIntrinsic()
OBAccelIntrinsic ob::AccelStreamProfile::getIntrinsic () const inline
get the intrinsic parameters of the stream.
Returns
OBAccelIntrinsic Return the intrinsic parameters.
Definition at line 307 of file StreamProfile.hpp.
fullScaleRange()
OBAccelFullScaleRange ob::AccelStreamProfile::fullScaleRange () const inline
Definition at line 316 of file StreamProfile.hpp.
Referenced by getFullScaleRange().
sampleRate()
OBAccelSampleRate ob::AccelStreamProfile::sampleRate () const inline
Definition at line 320 of file StreamProfile.hpp.
Referenced by getSampleRate().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/StreamProfile.hpp