OrbbecSDK: ob::OBDepthWorkModeList Class Reference
ob::OBDepthWorkModeList Class Reference
#include <Device.hpp>
Public Member Functions
OBDepthWorkModeList (ob_depth_work_mode_list_t *impl)
~OBDepthWorkModeList ()
uint32_t getCount ()
Get the number of OBDepthWorkMode objects in the list.
OBDepthWorkMode getOBDepthWorkMode (uint32_t index)
Get the OBDepthWorkMode object at the specified index.
OBDepthWorkMode operator[] (uint32_t index)
Get the OBDepthWorkMode object at the specified index.
uint32_t count ()
Detailed Description
Definition at line 1304 of file Device.hpp.
Constructor & Destructor Documentation
OBDepthWorkModeList()
ob::OBDepthWorkModeList::OBDepthWorkModeList (ob_depth_work_mode_list_t * impl) inline explicit
Definition at line 1309 of file Device.hpp.
~OBDepthWorkModeList()
ob::OBDepthWorkModeList::~OBDepthWorkModeList () inline
Definition at line 1310 of file Device.hpp.
Member Function Documentation
getCount()
uint32_t ob::OBDepthWorkModeList::getCount () inline
Get the number of OBDepthWorkMode objects in the list.
Returns
uint32_t the number of OBDepthWorkMode objects in the list
Definition at line 1321 of file Device.hpp.
Referenced by count().
getOBDepthWorkMode()
OBDepthWorkMode ob::OBDepthWorkModeList::getOBDepthWorkMode (uint32_t index) inline
Get the OBDepthWorkMode object at the specified index.
Parameters
index the index of the target OBDepthWorkMode object
Returns
OBDepthWorkMode the OBDepthWorkMode object at the specified index
Definition at line 1334 of file Device.hpp.
Referenced by operator[]().
operator[]()
OBDepthWorkMode ob::OBDepthWorkModeList::operator[] (uint32_t index) inline
Get the OBDepthWorkMode object at the specified index.
Parameters
index the index of the target OBDepthWorkMode object
Returns
OBDepthWorkMode the OBDepthWorkMode object at the specified index
Definition at line 1347 of file Device.hpp.
count()
uint32_t ob::OBDepthWorkModeList::count () inline
Definition at line 1353 of file Device.hpp.
Referenced by getCount().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/Device.hpp