OrbbecSDK: ob::GyroFrame Class Reference
ob::GyroFrame Class Reference
Define the GyroFrame class, which inherits from the Frame class.
#include <Frame.hpp>
Public Member Functions
GyroFrame (const ob_frame *impl)
~GyroFrame () noexcept override=default
OBGyroValue getValue () const
Get the gyro frame data.
float getTemperature () const
Get the temperature when the frame was sampled.
OBGyroValue value ()
float temperature ()
Public Member Functions inherited from ob::Frame
Frame (const ob_frame *impl)
Construct a new Frame object with a given pointer to the internal frame object.
const ob_frame * getImpl () const
Get the internal (impl) frame object.
virtual ~Frame () noexcept
Destroy the Frame object.
virtual OBFrameType getType () const
Get the type of frame.
virtual OBFormat getFormat () const
Get the format of the frame.
virtual uint64_t getIndex () const
Get the sequence number of the frame.
virtual uint8_t * getData () const
Get frame data.
virtual uint32_t getDataSize () const
Get the size of the frame data.
uint64_t getTimeStampUs () const
Get the hardware timestamp of the frame in microseconds.
uint64_t getSystemTimeStampUs () const
Get the system timestamp of the frame in microseconds.
uint64_t getGlobalTimeStampUs () const
Get the global timestamp of the frame in microseconds.
uint8_t * getMetadata () const
Get the metadata pointer of the frame.
uint32_t getMetadataSize () const
Get the size of the metadata of the frame.
bool hasMetadata (OBFrameMetadataType type) const
Check if the frame object has metadata of a given type.
int64_t getMetadataValue (OBFrameMetadataType type) const
Get the metadata value.
std::shared_ptr< StreamProfile > getStreamProfile () const
get StreamProfile of the frame
std::shared_ptr< Sensor > getSensor () const
get owner sensor of the frame
std::shared_ptr< Device > getDevice () const
get owner device of the frame
template<typename T>
bool is () const
Check if the runtime type of the frame object is compatible with a given type.
template<typename T>
std::shared_ptr< T > as ()
Convert the frame object to a target type.
template<typename T>
std::shared_ptr< const T > as () const
Convert the frame object to a target type.
OBFrameType type () const
virtual OBFormat format () const
virtual uint64_t index () const
virtual void * data () const
virtual uint32_t dataSize () const
uint64_t timeStamp () const
uint64_t timeStampUs () const
uint64_t systemTimeStamp () const
uint64_t systemTimeStampUs () const
uint64_t globalTimeStampUs () const
uint8_t * metadata () const
uint32_t metadataSize () const
Additional Inherited Members
Protected Attributes inherited from ob::Frame
const ob_frame * impl_ = nullptr
The pointer to the internal (c api level) frame object.
Detailed Description
Define the GyroFrame class, which inherits from the Frame class.
Definition at line 701 of file Frame.hpp.
Constructor & Destructor Documentation
GyroFrame()
ob::GyroFrame::GyroFrame (const ob_frame * impl) inline explicit
Definition at line 704 of file Frame.hpp.
~GyroFrame()
ob::GyroFrame::~GyroFrame () override default noexcept
Member Function Documentation
getValue()
OBGyroValue ob::GyroFrame::getValue () const inline
Get the gyro frame data.
Returns
OBAccelValue The gyro frame data
Definition at line 713 of file Frame.hpp.
Referenced by getValue(), and value().
getTemperature()
float ob::GyroFrame::getTemperature () const inline
Get the temperature when the frame was sampled.
Returns
float The temperature value in celsius
Definition at line 726 of file Frame.hpp.
Referenced by temperature().
value()
OBGyroValue ob::GyroFrame::value () inline
Definition at line 736 of file Frame.hpp.
Referenced by getValue().
temperature()
float ob::GyroFrame::temperature () inline
Definition at line 740 of file Frame.hpp.
Referenced by getTemperature().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/Frame.hpp