OrbbecSDK: ob::StreamProfileFactory Class Reference
ob::StreamProfileFactory Class Reference
#include <StreamProfile.hpp>
Static Public Member Functions
static std::shared_ptr< StreamProfile > create (const ob_stream_profile_t *impl)
Detailed Description
Definition at line 401 of file StreamProfile.hpp.
Member Function Documentation
create()
static std::shared_ptr< StreamProfile > ob::StreamProfileFactory::create (const ob_stream_profile_t * impl) inline static
Definition at line 403 of file StreamProfile.hpp.
Referenced by ob::StreamProfileList::getAccelStreamProfile(), ob::StreamProfileList::getGyroStreamProfile(), ob::StreamProfileList::getProfile(), ob::Frame::getStreamProfile(), and ob::StreamProfileList::getVideoStreamProfile().
The documentation for this class was generated from the following file:
D:/orbbec/openorbbecsdkgroup/OpenOrbbecSDK/include/libobsensor/hpp/StreamProfile.hpp