OrbbecSDK: ob::Frame Class Reference
ob::Frame Class Reference
Define the frame class, which is the base class of all frame types.
#include <Frame.hpp>
Public Member Functions
Frame (const ob_frame *impl)
Construct a new Frame object with a given pointer to the internal frame object.
const ob_frame * getImpl () const
Get the internal (impl) frame object.
virtual ~Frame () noexcept
Destroy the Frame object.
virtual OBFrameType getType () const
Get the type of frame.
virtual OBFormat getFormat () const
Get the format of the frame.
virtual uint64_t getIndex () const
Get the sequence number of the frame.
virtual uint8_t * getData () const
Get frame data.
virtual uint32_t getDataSize () const
Get the size of the frame data.
uint64_t getTimeStampUs () const
Get the hardware timestamp of the frame in microseconds.
uint64_t getSystemTimeStampUs () const
Get the system timestamp of the frame in microseconds.
uint64_t getGlobalTimeStampUs () const
Get the global timestamp of the frame in microseconds.
uint8_t * getMetadata () const
Get the metadata pointer of the frame.
uint32_t getMetadataSize () const
Get the size of the metadata of the frame.
bool hasMetadata (OBFrameMetadataType type) const
Check if the frame object has metadata of a given type.
int64_t getMetadataValue (OBFrameMetadataType type) const
Get the metadata value.
std::shared_ptr< StreamProfile > getStreamProfile () const
get StreamProfile of the frame
std::shared_ptr< Sensor > getSensor () const
get owner sensor of the frame
std::shared_ptr< Device > getDevice () const
get owner device of the frame
template<typename T>
bool is () const
Check if the runtime type of the frame object is compatible with a given type.
template<typename T>
std::shared_ptr< T > as ()
Convert the frame object to a target type.
template<typename T>
std::shared_ptr< const T > as () const
Convert the frame object to a target type.
void copyFrameInfo (std::shared_ptr< const Frame > srcFrame)
Copy the information of the source frame object to the destination frame object.
void setSystemTimestampUs (uint64_t systemTimestampUs)
Set the system timestamp of the frame in microseconds.
void updateData (const uint8_t *data, uint32_t dataSize)
Update the data of a frame.
void updateMetadata (const uint8_t *metadata, uint32_t metadataSize)
Update the metadata of the frame.
void setStreamProfile (std::shared_ptr< const StreamProfile > profile)
Set (override) the stream profile of the frame.
OBFrameType type () const
virtual OBFormat format () const
virtual uint64_t index () const
virtual void * data () const
virtual uint32_t dataSize () const
uint64_t timeStamp () const
uint64_t timeStampUs () const
uint64_t systemTimeStamp () const
uint64_t systemTimeStampUs () const
uint64_t globalTimeStampUs () const
uint8_t * metadata () const
uint32_t metadataSize () const
Protected Attributes
const ob_frame * impl_ = nullptr
The pointer to the internal (c api level) frame object.
Detailed Description
Define the frame class, which is the base class of all frame types.
Definition at line 45 of file Frame.hpp.
Constructor & Destructor Documentation
Frame()
ob::Frame::Frame (const ob_frame * impl) inline explicit
Construct a new Frame object with a given pointer to the internal frame object.
Attention
After calling this constructor, the frame object will own the internal frame object, and the internal frame object will be deleted when the frame object is destroyed.
The internal frame object should not be deleted by the caller.
Parameters
[in] impl The pointer to the internal frame object.
Definition at line 62 of file Frame.hpp.
Referenced by ob::AccelFrame::AccelFrame(), ob::FrameSet::FrameSet(), ob::GyroFrame::GyroFrame(), ob::LiDARPointsFrame::LiDARPointsFrame(), ob::PointsFrame::PointsFrame(), and ob::VideoFrame::VideoFrame().
~Frame()
virtual ob::Frame::~Frame () inline virtual noexcept
Destroy the Frame object.
Definition at line 76 of file Frame.hpp.
Member Function Documentation
getImpl()
const ob_frame * ob::Frame::getImpl () const inline
Get the internal (impl) frame object.
Returns
const ob_frame* the pointer to the internal frame object.
Definition at line 69 of file Frame.hpp.
getType()
virtual OBFrameType ob::Frame::getType () const inline virtual
Get the type of frame.
Returns
OBFrameType The type of frame.
Definition at line 90 of file Frame.hpp.
Referenced by is(), and type().
getFormat()
virtual OBFormat ob::Frame::getFormat () const inline virtual
Get the format of the frame.
Returns
OBFormat The format of the frame.
Definition at line 103 of file Frame.hpp.
Referenced by format().
getIndex()
virtual uint64_t ob::Frame::getIndex () const inline virtual
Get the sequence number of the frame.
Note
The sequence number for each frame is managed by the SDK. It increments by 1 for each frame on each stream.
Returns
uint64_t The sequence number of the frame.
Definition at line 118 of file Frame.hpp.
Referenced by index().
getData()
virtual uint8_t * ob::Frame::getData () const inline virtual
Get frame data.
Returns
const uint8_t * The frame data pointer.
Definition at line 131 of file Frame.hpp.
Referenced by data().
getDataSize()
virtual uint32_t ob::Frame::getDataSize () const inline virtual
Get the size of the frame data.
Returns
uint32_t The size of the frame data. For point cloud data, this returns the number of bytes occupied by all point sets. To find the number of points, divide the dataSize by the structure size of the corresponding point type.
Definition at line 146 of file Frame.hpp.
Referenced by dataSize().
getTimeStampUs()
uint64_t ob::Frame::getTimeStampUs () const inline
Get the hardware timestamp of the frame in microseconds.
The hardware timestamp is the time point when the frame was captured by the device, on device clock domain.
Returns
uint64_t The hardware timestamp of the frame in microseconds.
Definition at line 160 of file Frame.hpp.
Referenced by timeStamp(), and timeStampUs().
getSystemTimeStampUs()
uint64_t ob::Frame::getSystemTimeStampUs () const inline
Get the system timestamp of the frame in microseconds.
The system timestamp is the time point when the frame was received by the host, on host clock domain.
Returns
uint64_t The system timestamp of the frame in microseconds.
Definition at line 174 of file Frame.hpp.
Referenced by systemTimeStamp(), and systemTimeStampUs().
getGlobalTimeStampUs()
uint64_t ob::Frame::getGlobalTimeStampUs () const inline
Get the global timestamp of the frame in microseconds.
The global timestamp is the time point when the frame was captured by the device, and has been converted to the host clock domain. The conversion process base on the device timestamp and can eliminate the timer drift of the device
Attention
The global timestamp disable by default. If global timestamp is not enabled, the function will return 0. To enable the global timestamp, please call Device::enableGlobalTimestamp() function.
Only some devices support getting the global timestamp. Check the device support status by Device::isGlobalTimestampSupported() function.
Returns
uint64_t The global timestamp of the frame in microseconds.
Definition at line 193 of file Frame.hpp.
Referenced by globalTimeStampUs().
getMetadata()
uint8_t * ob::Frame::getMetadata () const inline
Get the metadata pointer of the frame.
Returns
const uint8_t * The metadata pointer of the frame.
Definition at line 206 of file Frame.hpp.
Referenced by metadata().
getMetadataSize()
uint32_t ob::Frame::getMetadataSize () const inline
Get the size of the metadata of the frame.
Returns
uint32_t The size of the metadata of the frame.
Definition at line 219 of file Frame.hpp.
Referenced by metadataSize().
hasMetadata()
bool ob::Frame::hasMetadata (OBFrameMetadataType type) const inline
Check if the frame object has metadata of a given type.
Parameters
[in] type The metadata type. refer to OBFrameMetadataType
Returns
bool The result.
Definition at line 234 of file Frame.hpp.
getMetadataValue()
int64_t ob::Frame::getMetadataValue (OBFrameMetadataType type) const inline
Get the metadata value.
Parameters
[in] type The metadata type. refer to OBFrameMetadataType
Returns
int64_t The metadata value.
Definition at line 249 of file Frame.hpp.
getStreamProfile()
std::shared_ptr< StreamProfile > ob::Frame::getStreamProfile () const inline
get StreamProfile of the frame
Returns
std::shared_ptr<StreamProfile> The StreamProfile of the frame, may return nullptr if the frame is not captured from a stream.
Definition at line 262 of file Frame.hpp.
getSensor()
std::shared_ptr< Sensor > ob::Frame::getSensor () const inline
get owner sensor of the frame
Returns
std::shared_ptr<Sensor> The owner sensor of the frame, return nullptr if the frame is not owned by any sensor or the sensor is destroyed
Definition at line 274 of file Frame.hpp.
getDevice()
std::shared_ptr< Device > ob::Frame::getDevice () const inline
get owner device of the frame
Returns
std::shared_ptr<Device> The owner device of the frame, return nullptr if the frame is not owned by any device or the device is destroyed
Definition at line 287 of file Frame.hpp.
is()
template<typename T> bool ob::Frame::is () const
Check if the runtime type of the frame object is compatible with a given type.
Template Parameters
T The given type.
Returns
bool The result.
Definition at line 1287 of file Frame.hpp.
Referenced by as(), as(), and is().
as() [1/2]
template<typename T> std::shared_ptr< T > ob::Frame::as () inline
Convert the frame object to a target type.
Template Parameters
T The target type.
Returns
std::shared_ptr<T> The result. If it cannot be converted, an exception will be thrown.
Definition at line 311 of file Frame.hpp.
as() [2/2]
template<typename T> std::shared_ptr< const T > ob::Frame::as () const inline
Convert the frame object to a target type.
Template Parameters
T The target type.
Returns
std::shared_ptr<T> The result. If it cannot be converted, an exception will be thrown.
Definition at line 330 of file Frame.hpp.
copyFrameInfo()
void ob::Frame::copyFrameInfo (std::shared_ptr< const Frame > srcFrame) inline
Copy the information of the source frame object to the destination frame object.
Including the index, timestamp, system timestamp, global timestamp and metadata will be copied.
Parameters
[in] srcFrame Source frame object to copy the information from.
Definition at line 348 of file Frame.hpp.
setSystemTimestampUs()
void ob::Frame::setSystemTimestampUs (uint64_t systemTimestampUs) inline
Set the system timestamp of the frame in microseconds.
Parameters
systemTimestampUs frame system timestamp to set in microseconds.
Definition at line 361 of file Frame.hpp.
updateData()
void ob::Frame::updateData (const uint8_t * data, uint32_t dataSize) inline
Update the data of a frame.
The data will be memcpy to the frame data buffer.
The frame data size will be also updated as the input data size.
Attention
It is not recommended to update the frame data if the frame was not created by the user. If you must update it, ensure that the frame is not being used in other threads.
The size of the new data should be equal to or less than the current data size of the frame. Exceeding the original size may cause memory exceptions.
Parameters
[in] data The new data to update the frame with.
[in] dataSize The size of the new data.
Definition at line 382 of file Frame.hpp.
updateMetadata()
void ob::Frame::updateMetadata (const uint8_t * metadata, uint32_t metadataSize) inline
Update the metadata of the frame.
The metadata will be memcpy to the frame metadata buffer.
The frame metadata size will be also updated as the input metadata size.
Attention
It is not recommended to update the frame metadata if the frame was not created by the user. If you must update it, ensure that the frame is not being used in other threads or future use.
The metadata size should be equal to or less than 256 bytes, otherwise it will cause memory exception.
Parameters
[in] metadata The new metadata to update.
[in] metadataSize The size of the new metadata.
Definition at line 402 of file Frame.hpp.
setStreamProfile()
void ob::Frame::setStreamProfile (std::shared_ptr< const StreamProfile > profile) inline
Set (override) the stream profile of the frame.
Parameters
profile The stream profile to set for the frame.
Definition at line 415 of file Frame.hpp.
type()
OBFrameType ob::Frame::type () const inline
Definition at line 425 of file Frame.hpp.
Referenced by getMetadataValue(), getType(), and hasMetadata().
format()
virtual OBFormat ob::Frame::format () const inline virtual
Definition at line 429 of file Frame.hpp.
Referenced by getFormat().
index()
virtual uint64_t ob::Frame::index () const inline virtual
Definition at line 433 of file Frame.hpp.
Referenced by ob::FrameSet::getFrame(), ob::FrameSet::getFrameByIndex(), and getIndex().
data()
virtual void * ob::Frame::data () const inline virtual
Definition at line 437 of file Frame.hpp.
Referenced by data(), getData(), and updateData().
dataSize()
virtual uint32_t ob::Frame::dataSize () const inline virtual
Definition at line 442 of file Frame.hpp.
Referenced by getDataSize(), and updateData().
timeStamp()
uint64_t ob::Frame::timeStamp () const inline
Definition at line 446 of file Frame.hpp.
timeStampUs()
uint64_t ob::Frame::timeStampUs () const inline
Definition at line 450 of file Frame.hpp.
Referenced by getTimeStampUs().
systemTimeStamp()
uint64_t ob::Frame::systemTimeStamp () const inline
Definition at line 454 of file Frame.hpp.
systemTimeStampUs()
uint64_t ob::Frame::systemTimeStampUs () const inline
Definition at line 458 of file Frame.hpp.
Referenced by getSystemTimeStampUs().
globalTimeStampUs()
uint64_t ob::Frame::globalTimeStampUs () const inline
Definition at line 462 of file Frame.hpp.
Referenced by getGlobalTimeStampUs().
metadata()
uint8_t * ob::Frame::metadata () const inline
Definition at line 466 of file Frame.hpp.
Referenced by getMetadata(), and updateMetadata().
metadataSize()
uint32_t ob::Frame::metadataSize () const inline
Definition at line 470 of file Frame.hpp.
Referenced by getMetadataSize(), and updateMetadata().
Member Data Documentation
impl_
const ob_frame* ob::Frame::impl_ = nullptr protected
The pointer to the internal (c api level) frame object.
Definition at line 50 of file Frame.hpp.
Referenced by as(), as(), copyFrameInfo(), Frame(), ob::FrameSet::getColorFrame(), ob::PointsFrame::getCoordinateValueScale(), ob::FrameSet::getCount(), getData(), getDataSize(), ob::FrameSet::getDepthFrame(), getDevice(), getFormat(), ob::FrameSet::getFrame(), ob::FrameSet::getFrameByIndex(), getGlobalTimeStampUs(), ob::PointsFrame::getHeight(), ob::VideoFrame::getHeight(), getImpl(), getIndex(), ob::FrameSet::getIrFrame(), getMetadata(), getMetadataSize(), getMetadataValue(), ob::VideoFrame::getPixelAvailableBitSize(), ob::VideoFrame::getPixelType(), ob::FrameSet::getPointsFrame(), getSensor(), getStreamProfile(), getSystemTimeStampUs(), ob::AccelFrame::getTemperature(), ob::GyroFrame::getTemperature(), getTimeStampUs(), getType(), ob::AccelFrame::getValue(), ob::GyroFrame::getValue(), ob::DepthFrame::getValueScale(), ob::PointsFrame::getWidth(), ob::VideoFrame::getWidth(), hasMetadata(), ob::FrameSet::pushFrame(), ob::VideoFrame::setPixelAvailableBitSize(), ob::VideoFrame::setPixelType(), setStreamProfile(), setSystemTimestampUs(), ob::DepthFrame::setValueScale(), updateData(), updateMetadata(), and ~Frame().
The documentation for this class was generated from the following file:
Frame.hpp