OrbbecSDK: ob::DeviceList Class Reference
ob::DeviceList Class Reference
Class representing a list of devices.
#include <Device.hpp>
Public Member Functions
DeviceList (ob_device_list_t *impl)
~DeviceList () noexcept
uint32_t getCount () const
Get the number of devices in the list.
int getPid (uint32_t index) const
Get the PID of the device at the specified index.
int getVid (uint32_t index) const
Get the VID of the device at the specified index.
const char * getUid (uint32_t index) const
Get the UID of the device at the specified index.
const char * getSerialNumber (uint32_t index) const
Get the serial number of the device at the specified index.
const char * getName (uint32_t index) const
Get the name of the device at the specified index in the device list.
const char * getConnectionType (uint32_t index) const
Get device connection type.
const char * getIpAddress (uint32_t index) const
get the ip address of the device at the specified index
const char * getSubnetMask (uint32_t index) const
get the subnet mask of the device at the specified index
const char * getGateway (uint32_t index) const
get the gateway of the device at the specified index
const char * getLocalMacAddress (uint32_t index) const
Get the MAC address of the host network interface corresponding to the device at the specified index.
const char * getLocalIP (uint32_t index) const
Get the IP address of the host network interface corresponding to the device at the specified index.
uint8_t getLocalSubnetLength (uint32_t index) const
Get the subnet length of the host network interface corresponding to the device at the specified index.
const char * getLocalGateway (uint32_t index) const
Get the gateway of the host network interface corresponding to the device at the specified index.
std::shared_ptr< Device > getDevice (uint32_t index, OBDeviceAccessMode accessMode=OB_DEVICE_DEFAULT_ACCESS) const
Get the device object at the specified index.
std::shared_ptr< Device > getDeviceBySN (const char *serialNumber, OBDeviceAccessMode accessMode=OB_DEVICE_DEFAULT_ACCESS) const
Get the device object with the specified serial number.
std::shared_ptr< Device > getDeviceByUid (const char *uid, OBDeviceAccessMode accessMode=OB_DEVICE_DEFAULT_ACCESS) const
Get the specified device object from the device list by uid.
uint32_t deviceCount () const
int pid (uint32_t index) const
int vid (uint32_t index) const
const char * uid (uint32_t index) const
const char * serialNumber (uint32_t index) const
const char * name (uint32_t index) const
const char * connectionType (uint32_t index) const
const char * ipAddress (uint32_t index) const
Detailed Description
Class representing a list of devices.
Definition at line 1130 of file Device.hpp.
Constructor & Destructor Documentation
DeviceList()
ob::DeviceList::DeviceList (ob_device_list_t * impl) inline explicit
Definition at line 1135 of file Device.hpp.
~DeviceList()
ob::DeviceList::~DeviceList () inline noexcept
Definition at line 1136 of file Device.hpp.
Member Function Documentation
getCount()
uint32_t ob::DeviceList::getCount () const inline
Get the number of devices in the list.
Returns
uint32_t the number of devices in the list
Definition at line 1147 of file Device.hpp.
Referenced by deviceCount().
getPid()
int ob::DeviceList::getPid (uint32_t index) const inline
Get the PID of the device at the specified index.
Parameters
[in] index the index of the device
Returns
int the PID of the device
Definition at line 1161 of file Device.hpp.
Referenced by pid().
getVid()
int ob::DeviceList::getVid (uint32_t index) const inline
Get the VID of the device at the specified index.
Parameters
[in] index the index of the device
Returns
int the VID of the device
Definition at line 1175 of file Device.hpp.
Referenced by vid().
getUid()
const char * ob::DeviceList::getUid (uint32_t index) const inline
Get the UID of the device at the specified index.
Parameters
[in] index the index of the device
Returns
const char* the UID of the device
Definition at line 1189 of file Device.hpp.
Referenced by uid().
getSerialNumber()
const char * ob::DeviceList::getSerialNumber (uint32_t index) const inline
Get the serial number of the device at the specified index.
Parameters
[in] index the index of the device
Returns
const char* the serial number of the device
Definition at line 1203 of file Device.hpp.
Referenced by serialNumber().
getName()
const char * ob::DeviceList::getName (uint32_t index) const inline
Get the name of the device at the specified index in the device list.
This function retrieves the name of the device at the given index in the device list. If an error occurs during the operation, it will be handled by the Error::handle function.
Parameters
[in] index The index of the device in the device list.
Returns
const char* The name of the device at the specified index.
Definition at line 1220 of file Device.hpp.
Referenced by name().
getConnectionType()
const char * ob::DeviceList::getConnectionType (uint32_t index) const inline
Get device connection type.
Parameters
[in] index device index
Returns
const char* returns connection type, currently supports: "USB", "USB1.0", "USB1.1", "USB2.0", "USB2.1", "USB3.0", "USB3.1", "USB3.2", "Ethernet", "GMSL2"
Definition at line 1235 of file Device.hpp.
Referenced by connectionType().
getIpAddress()
const char * ob::DeviceList::getIpAddress (uint32_t index) const inline
get the ip address of the device at the specified index
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
[in] index the index of the device
Returns
const char* the ip address of the device
Definition at line 1251 of file Device.hpp.
Referenced by ipAddress().
getSubnetMask()
const char * ob::DeviceList::getSubnetMask (uint32_t index) const inline
get the subnet mask of the device at the specified index
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
[in] index the index of the device
Returns
const char* the subnet mask of the device
Definition at line 1267 of file Device.hpp.
getGateway()
const char * ob::DeviceList::getGateway (uint32_t index) const inline
get the gateway of the device at the specified index
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
[in] index the index of the device
Returns
const char* the gateway of the device
Definition at line 1283 of file Device.hpp.
getLocalMacAddress()
const char * ob::DeviceList::getLocalMacAddress (uint32_t index) const inline
Get the MAC address of the host network interface corresponding to the device at the specified index.
Attention
Only valid for network devices, otherwise it will return "0:0:0:0:0:0".
Parameters
[in] index the index of the device
Returns
const char* The MAC address of the host network interface associated with the device.
Definition at line 1299 of file Device.hpp.
getLocalIP()
const char * ob::DeviceList::getLocalIP (uint32_t index) const inline
Get the IP address of the host network interface corresponding to the device at the specified index.
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
[in] index The index of the device
Returns
const char* The IP address of the host network interface associated with the device.
Definition at line 1315 of file Device.hpp.
getLocalSubnetLength()
uint8_t ob::DeviceList::getLocalSubnetLength (uint32_t index) const inline
Get the subnet length of the host network interface corresponding to the device at the specified index.
Attention
Only valid for network devices, otherwise it will return 0.
Parameters
[in] index The index of the device
Returns
uint8_t The subnet length (0~32) of the host network interface associated with the device.
Definition at line 1331 of file Device.hpp.
getLocalGateway()
const char * ob::DeviceList::getLocalGateway (uint32_t index) const inline
Get the gateway of the host network interface corresponding to the device at the specified index.
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Parameters
[in] index The index of the device
Returns
const char* The gateway of the host network interface associated with the device.
Definition at line 1347 of file Device.hpp.
getDevice()
std::shared_ptr< Device > ob::DeviceList::getDevice (uint32_t index, OBDeviceAccessMode accessMode = OB_DEVICE_DEFAULT_ACCESS) const inline
Get the device object at the specified index.
Attention
If the device has already been acquired and created elsewhere, repeated acquisition will throw an exception
Parameters
[in] index the index of the device to create
[in] accessMode Device access mode. ob_device_access_mode. If the device does not support setting the Access Mode, the default OB_DEVICE_DEFAULT_ACCESS is used. Applies only on first device creation or after release and re-creation; subsequent calls ignore it.
Returns
std::shared_ptr<Device> the device object
Definition at line 1366 of file Device.hpp.
getDeviceBySN()
std::shared_ptr< Device > ob::DeviceList::getDeviceBySN (const char * serialNumber, OBDeviceAccessMode accessMode = OB_DEVICE_DEFAULT_ACCESS) const inline
Get the device object with the specified serial number.
Attention
If the device has already been acquired and created elsewhere, repeated acquisition will throw an exception
Parameters
[in] serialNumber the serial number of the device to create
[in] accessMode Device access mode. ob_device_access_mode. If the device does not support setting the Access Mode, the default OB_DEVICE_DEFAULT_ACCESS is used. Applies only on first device creation or after release and re-creation; subsequent calls ignore it.
Returns
std::shared_ptr<Device> the device object
Definition at line 1385 of file Device.hpp.
getDeviceByUid()
std::shared_ptr< Device > ob::DeviceList::getDeviceByUid (const char * uid, OBDeviceAccessMode accessMode = OB_DEVICE_DEFAULT_ACCESS) const inline
Get the specified device object from the device list by uid.
On Linux platform, for usb device, the uid of the device is composed of bus-port-dev, for example 1-1.2-1. But the SDK will remove the dev number and only keep the bus-port as the uid to create the device, for example 1-1.2, so that we can create a device connected to the specified USB port. Similarly, users can also directly pass in bus-port as uid to create device.
For GMSL device, the uid is GMSL port with "gmsl2-" prefix, for example gmsl2-1.
Attention
If the device has been acquired and created elsewhere, repeated acquisition will throw an exception
Parameters
[in] uid The uid of the device to be created
[in] accessMode Device access mode. ob_device_access_mode. If the device does not support setting the Access Mode, the default OB_DEVICE_DEFAULT_ACCESS is used. Applies only on first device creation or after release and re-creation; subsequent calls ignore it.
Returns
std::shared_ptr<Device> returns the device object
Definition at line 1408 of file Device.hpp.
deviceCount()
uint32_t ob::DeviceList::deviceCount () const inline
Definition at line 1417 of file Device.hpp.
pid()
int ob::DeviceList::pid (uint32_t index) const inline
Definition at line 1421 of file Device.hpp.
Referenced by getPid().
vid()
int ob::DeviceList::vid (uint32_t index) const inline
Definition at line 1425 of file Device.hpp.
Referenced by getVid().
uid()
const char * ob::DeviceList::uid (uint32_t index) const inline
Definition at line 1429 of file Device.hpp.
Referenced by getDeviceByUid(), and getUid().
serialNumber()
const char * ob::DeviceList::serialNumber (uint32_t index) const inline
Definition at line 1433 of file Device.hpp.
Referenced by getDeviceBySN().
name()
const char * ob::DeviceList::name (uint32_t index) const inline
Definition at line 1437 of file Device.hpp.
Referenced by getName().
connectionType()
const char * ob::DeviceList::connectionType (uint32_t index) const inline
Definition at line 1441 of file Device.hpp.
ipAddress()
const char * ob::DeviceList::ipAddress (uint32_t index) const inline
Definition at line 1445 of file Device.hpp.
The documentation for this class was generated from the following file:
Device.hpp