OrbbecSDK: ob::TypeHelper Class Reference
ob::TypeHelper Class Reference
#include <TypeHelper.hpp>
Static Public Member Functions
static std::string convertOBFormatTypeToString (const OBFormat &type)
Convert OBFormat to " string " type and then return.
static std::string convertOBFrameTypeToString (const OBFrameType &type)
Convert OBFrameType to " string " type and then return.
static std::string convertOBStreamTypeToString (const OBStreamType &type)
Convert OBStreamType to " string " type and then return.
static std::string convertOBSensorTypeToString (const OBSensorType &type)
Convert OBSensorType to " string " type and then return.
static std::string convertOBIMUSampleRateTypeToString (const OBIMUSampleRate &type)
Convert OBIMUSampleRate to " string " type and then return.
static std::string convertOBGyroFullScaleRangeTypeToString (const OBGyroFullScaleRange &type)
Convert OBGyroFullScaleRange to " string " type and then return.
static std::string convertOBAccelFullScaleRangeTypeToString (const OBAccelFullScaleRange &type)
Convert OBAccelFullScaleRange to " string " type and then return.
static std::string convertOBFrameMetadataTypeToString (const OBFrameMetadataType &type)
Convert OBFrameMetadataType to " string " type and then return.
static OBStreamType convertSensorTypeToStreamType (OBSensorType type)
Convert OBSensorType to OBStreamType type and then return.
static bool isVideoSensorType (OBSensorType type)
Check if the given sensor type is a video sensor.
static bool isVideoStreamType (OBStreamType type)
Check if the given stream type is a video stream.
Detailed Description
Definition at line 14 of file TypeHelper.hpp.
Member Function Documentation
convertOBFormatTypeToString()
static std::string ob::TypeHelper::convertOBFormatTypeToString (const OBFormat & type) inline static
Convert OBFormat to " string " type and then return.
Parameters
[in] type OBFormat type.
Returns
OBFormat of "string" type.
Definition at line 22 of file TypeHelper.hpp.
convertOBFrameTypeToString()
static std::string ob::TypeHelper::convertOBFrameTypeToString (const OBFrameType & type) inline static
Convert OBFrameType to " string " type and then return.
Parameters
[in] type OBFrameType type.
Returns
OBFrameType of "string" type.
Definition at line 32 of file TypeHelper.hpp.
convertOBStreamTypeToString()
static std::string ob::TypeHelper::convertOBStreamTypeToString (const OBStreamType & type) inline static
Convert OBStreamType to " string " type and then return.
Parameters
[in] type OBStreamType type.
Returns
OBStreamType of "string" type.
Definition at line 42 of file TypeHelper.hpp.
convertOBSensorTypeToString()
static std::string ob::TypeHelper::convertOBSensorTypeToString (const OBSensorType & type) inline static
Convert OBSensorType to " string " type and then return.
Parameters
[in] type OBSensorType type.
Returns
OBSensorType of "string" type.
Definition at line 52 of file TypeHelper.hpp.
convertOBIMUSampleRateTypeToString()
static std::string ob::TypeHelper::convertOBIMUSampleRateTypeToString (const OBIMUSampleRate & type) inline static
Convert OBIMUSampleRate to " string " type and then return.
Parameters
[in] type OBIMUSampleRate type.
Returns
OBIMUSampleRate of "string" type.
Definition at line 62 of file TypeHelper.hpp.
convertOBGyroFullScaleRangeTypeToString()
static std::string ob::TypeHelper::convertOBGyroFullScaleRangeTypeToString (const OBGyroFullScaleRange & type) inline static
Convert OBGyroFullScaleRange to " string " type and then return.
Parameters
[in] type OBGyroFullScaleRange type.
Returns
OBGyroFullScaleRange of "string" type.
Definition at line 72 of file TypeHelper.hpp.
convertOBAccelFullScaleRangeTypeToString()
static std::string ob::TypeHelper::convertOBAccelFullScaleRangeTypeToString (const OBAccelFullScaleRange & type) inline static
Convert OBAccelFullScaleRange to " string " type and then return.
Parameters
[in] type OBAccelFullScaleRange type.
Returns
OBAccelFullScaleRange of "string" type.
Definition at line 82 of file TypeHelper.hpp.
convertOBFrameMetadataTypeToString()
static std::string ob::TypeHelper::convertOBFrameMetadataTypeToString (const OBFrameMetadataType & type) inline static
Convert OBFrameMetadataType to " string " type and then return.
Parameters
[in] type OBFrameMetadataType type.
Returns
OBFrameMetadataType of "string" type.
Definition at line 92 of file TypeHelper.hpp.
convertSensorTypeToStreamType()
static OBStreamType ob::TypeHelper::convertSensorTypeToStreamType (OBSensorType type) inline static
Convert OBSensorType to OBStreamType type and then return.
Parameters
[in] type OBSensorType type.
Returns
OBStreamType type.
Definition at line 102 of file TypeHelper.hpp.
Referenced by ob::Config::disableStream(), ob::Config::enableStream(), and ob::Config::enableVideoStream().
isVideoSensorType()
static bool ob::TypeHelper::isVideoSensorType (OBSensorType type) inline static
Check if the given sensor type is a video sensor.
Video sensors are sensors that produce video frames.
The following sensor types are considered video sensors: OB_SENSOR_COLOR, OB_SENSOR_DEPTH, OB_SENSOR_IR, OB_SENSOR_IR_LEFT, OB_SENSOR_IR_RIGHT,
Parameters
type
Returns
true
false
Definition at line 120 of file TypeHelper.hpp.
isVideoStreamType()
static bool ob::TypeHelper::isVideoStreamType (OBStreamType type) inline static
Check if the given stream type is a video stream.
Video streams are streams that contain video frames.
The following stream types are considered video streams: OB_STREAM_VIDEO, OB_STREAM_DEPTH, OB_STREAM_COLOR, OB_STREAM_IR, OB_STREAM_IR_LEFT, OB_STREAM_IR_RIGHT,
Parameters
type The stream type to check.
Returns
true if the given stream type is a video stream, false otherwise.
Definition at line 138 of file TypeHelper.hpp.
The documentation for this class was generated from the following file:
E:/orbbec/package/openorbbecsdkgroup/OpenOrbbecSDK/include/libobsensor/hpp/TypeHelper.hpp