OrbbecSDK: ob::Error Class Reference
ob::Error Class Reference
#include <Error.hpp>
Public Member Functions
~Error () override
Destroy the Error object.
const char * what () const noexcept override
Returns the error message of the exception.
OBExceptionType getExceptionType () const noexcept
Returns the exception type of the exception.
const char * getFunction () const noexcept
Returns the name of the function where the exception occurred.
const char * getArgs () const noexcept
Returns the arguments of the function where the exception occurred.
const char * getMessage () const noexcept
Returns the error message of the exception.
const char * getName () const noexcept
Static Public Member Functions
static void handle (ob_error **error, bool throw_exception=true)
A static function to handle the ob_error and throw an exception if needed.
Detailed Description
Definition at line 16 of file Error.hpp.
Constructor & Destructor Documentation
~Error()
ob::Error::~Error () inline override
Destroy the Error object.
Definition at line 55 of file Error.hpp.
Member Function Documentation
handle()
void ob::Error::handle (ob_error ** error, bool throw_exception = true) inline static
A static function to handle the ob_error and throw an exception if needed.
Parameters
[in,out] error The ob_error pointer to be handled.
[in] throw_exception A boolean value to indicate whether to throw an exception or not, the default value is true.
Definition at line 38 of file Error.hpp.
Referenced by ob::Align::Align(), ob::Frame::as(), ob::Frame::as(), ob::StreamProfile::bindExtrinsicTo(), ob::StreamProfile::bindExtrinsicTo(), ob::CoordinateTransformHelper::calibration2dTo2d(), ob::CoordinateTransformHelper::calibration2dTo3d(), ob::CoordinateTransformHelper::calibration3dTo2d(), ob::CoordinateTransformHelper::calibration3dTo3d(), ob::Config::Config(), ob::Context::Context(), ob::Frame::copyFrameInfo(), ob::StreamProfileFactory::create(), ob::FilterFactory::createFilter(), ob::FrameFactory::createFrame(), ob::FrameFactory::createFrameFromBuffer(), ob::FrameFactory::createFrameFromOtherFrame(), ob::FrameFactory::createFrameFromStreamProfile(), ob::FrameFactory::createFrameSet(), ob::Context::createNetDevice(), ob::FilterFactory::createPrivateFilter(), ob::Sensor::createRecommendedFilters(), ob::FrameFactory::createVideoFrame(), ob::FrameFactory::createVideoFrameFromBuffer(), ob::DecimationFilter::DecimationFilter(), ob::Config::disableAllStream(), ob::Pipeline::disableFrameSync(), ob::Config::disableStream(), ob::DisparityTransform::DisparityTransform(), ob::Filter::enable(), ob::Config::enableAccelStream(), ob::Config::enableAllStream(), ob::Context::enableDeviceClockSync(), ob::Pipeline::enableFrameSync(), ob::Device::enableGlobalTimestamp(), ob::Config::enableGyroStream(), ob::Device::enableHeartbeat(), ob::Config::enableLiDARStream(), ob::Context::enableNetDeviceEnumeration(), ob::Config::enableStream(), ob::Config::enableStream(), ob::Config::enableVideoStream(), ob::Device::exportSettingsAsPresetJsonFile(), ob::Context::forceIp(), ob::FormatConvertFilter::FormatConvertFilter(), ob::Context::freeIdleMemory(), ob::StreamProfileList::getAccelStreamProfile(), ob::DeviceInfo::getAsicName(), ob::Device::getAvailableFrameInterleaveList(), ob::Device::getAvailablePresetList(), ob::Device::getAvailablePresetResolutionConfigList(), ob::Device::getBoolProperty(), ob::Device::getBoolPropertyRange(), ob::Device::getCalibrationCameraParamList(), ob::Pipeline::getCalibrationParam(), ob::CameraParamList::getCameraParam(), ob::Pipeline::getCameraParam(), ob::Pipeline::getCameraParamWithProfile(), ob::FrameSet::getColorFrame(), ob::Pipeline::getConfig(), ob::Filter::getConfigSchema(), ob::Filter::getConfigValue(), ob::DeviceInfo::getConnectionType(), ob::DeviceList::getConnectionType(), ob::PointsFrame::getCoordinateValueScale(), ob::CameraParamList::getCount(), ob::DeviceFrameInterleaveList::getCount(), ob::DeviceList::getCount(), ob::DevicePresetList::getCount(), ob::FrameSet::getCount(), ob::OBDepthWorkModeList::getCount(), ob::OBFilterList::getCount(), ob::PresetResolutionConfigList::getCount(), ob::SensorList::getCount(), ob::StreamProfileList::getCount(), ob::Device::getCurrentDepthModeName(), ob::Device::getCurrentDepthWorkMode(), ob::Device::getCurrentPresetName(), ob::Pipeline::getD2CDepthProfileList(), ob::Frame::getData(), ob::Frame::getDataSize(), ob::FrameSet::getDepthFrame(), ob::Device::getDepthWorkModeList(), ob::DeviceList::getDevice(), ob::Frame::getDevice(), ob::Pipeline::getDevice(), ob::DeviceList::getDeviceBySN(), ob::DeviceList::getDeviceByUid(), ob::DeviceInfo::getDeviceGateway(), ob::Device::getDeviceInfo(), ob::DeviceInfo::getDeviceSubnetMask(), ob::DeviceInfo::getDeviceType(), ob::VideoStreamProfile::getDistortion(), ob::PlaybackDevice::getDuration(), ob::Config::getEnabledStreamProfileList(), ob::Device::getExtensionInfo(), ob::StreamProfile::getExtrinsicTo(), ob::OBFilterList::getFilter(), ob::FilterFactory::getFilterVendorSpecificCode(), ob::DeviceInfo::getFirmwareVersion(), ob::Device::getFloatProperty(), ob::Device::getFloatPropertyRange(), ob::Frame::getFormat(), ob::StreamProfile::getFormat(), ob::VideoStreamProfile::getFps(), ob::FrameSet::getFrame(), ob::FrameSet::getFrameByIndex(), ob::AccelStreamProfile::getFullScaleRange(), ob::GyroStreamProfile::getFullScaleRange(), ob::DeviceList::getGateway(), ob::Frame::getGlobalTimeStampUs(), ob::StreamProfileList::getGyroStreamProfile(), ob::DeviceInfo::getHardwareVersion(), ob::PointsFrame::getHeight(), ob::VideoFrame::getHeight(), ob::VideoStreamProfile::getHeight(), ob::Frame::getIndex(), ob::Device::getIntProperty(), ob::Device::getIntPropertyRange(), ob::AccelStreamProfile::getIntrinsic(), ob::GyroStreamProfile::getIntrinsic(), ob::VideoStreamProfile::getIntrinsic(), ob::DeviceInfo::getIpAddress(), ob::DeviceList::getIpAddress(), ob::FrameSet::getIrFrame(), ob::StreamProfileList::getLiDARStreamProfile(), ob::DeviceList::getLocalGateway(), ob::DeviceList::getLocalIP(), ob::DeviceList::getLocalMacAddress(), ob::DeviceList::getLocalSubnetLength(), ob::Frame::getMetadata(), ob::Frame::getMetadataSize(), ob::Frame::getMetadataValue(), ob::Device::getMultiDeviceSyncConfig(), ob::DeviceFrameInterleaveList::getName(), ob::DeviceInfo::getName(), ob::DeviceList::getName(), ob::DevicePresetList::getName(), ob::OBDepthWorkModeList::getOBDepthWorkMode(), ob::DeviceInfo::getPid(), ob::DeviceList::getPid(), ob::VideoFrame::getPixelAvailableBitSize(), ob::VideoFrame::getPixelType(), ob::PlaybackDevice::getPlaybackStatus(), ob::FrameSet::getPointsFrame(), ob::PlaybackDevice::getPosition(), ob::PresetResolutionConfigList::getPresetResolutionRatioConfig(), ob::StreamProfileList::getProfile(), ob::AccelStreamProfile::getSampleRate(), ob::GyroStreamProfile::getSampleRate(), ob::LiDARStreamProfile::getScanRate(), ob::Device::getSensor(), ob::Frame::getSensor(), ob::SensorList::getSensor(), ob::SensorList::getSensor(), ob::Device::getSensorList(), ob::SensorList::getSensorType(), ob::DeviceInfo::getSerialNumber(), ob::DeviceList::getSerialNumber(), ob::Frame::getStreamProfile(), ob::Pipeline::getStreamProfileList(), ob::Sensor::getStreamProfileList(), ob::Device::getStructuredData(), ob::DeviceList::getSubnetMask(), ob::DeviceInfo::getSupportedMinSdkVersion(), ob::Device::getSupportedMultiDeviceSyncModeBitmap(), ob::Device::getSupportedProperty(), ob::Device::getSupportedPropertyCount(), ob::Frame::getSystemTimeStampUs(), ob::AccelFrame::getTemperature(), ob::GyroFrame::getTemperature(), ob::Device::getTimestampResetConfig(), ob::Frame::getTimeStampUs(), ob::Frame::getType(), ob::Sensor::getType(), ob::StreamProfile::getType(), ob::DeviceInfo::getUid(), ob::DeviceList::getUid(), ob::AccelFrame::getValue(), ob::GyroFrame::getValue(), ob::DepthFrame::getValueScale(), ob::DeviceInfo::getVid(), ob::DeviceList::getVid(), ob::StreamProfileList::getVideoStreamProfile(), ob::PointsFrame::getWidth(), ob::VideoFrame::getWidth(), ob::VideoStreamProfile::getWidth(), ob::DeviceFrameInterleaveList::hasFrameInterleave(), ob::Frame::hasMetadata(), ob::DevicePresetList::hasPreset(), ob::HdrMerge::HdrMerge(), ob::HoleFillingFilter::HoleFillingFilter(), ob::Filter::init(), ob::Filter::isEnabled(), ob::Device::isExtensionInfoExist(), ob::Device::isFrameInterleaveSupported(), ob::Device::isGlobalTimestampSupported(), ob::Device::isPropertySupported(), ob::Device::loadFrameInterleave(), ob::Device::loadPreset(), ob::Device::loadPresetFromJsonFile(), ob::Context::logExternalMessage(), ob::NoiseRemovalFilter::NoiseRemovalFilter(), ob::Device::operator=(), ob::Sensor::operator=(), ob::StreamProfile::operator=(), ob::PlaybackDevice::pause(), ob::RecordDevice::pause(), ob::Pipeline::Pipeline(), ob::Pipeline::Pipeline(), ob::PlaybackDevice::PlaybackDevice(), ob::PointCloudFilter::PointCloudFilter(), ob::Filter::process(), ob::Filter::pushFrame(), ob::FrameSet::pushFrame(), ob::Context::queryDeviceList(), ob::Device::readCustomerData(), ob::Device::reboot(), ob::RecordDevice::RecordDevice(), ob::Context::registerDeviceChangedCallback(), ob::Filter::reset(), ob::PlaybackDevice::resume(), ob::RecordDevice::resume(), ob::PointCloudHelper::saveLiDARPointcloudToPly(), ob::PointCloudHelper::savePointcloudToPly(), ob::PlaybackDevice::seek(), ob::Device::sendAndReceiveData(), ob::SequenceIdFilter::SequenceIdFilter(), ob::Config::setAlignMode(), ob::Align::setAlignToStreamProfile(), ob::Device::setBoolProperty(), ob::Filter::setCallBack(), ob::Filter::setConfigValue(), ob::Config::setDepthScaleRequire(), ob::Device::setDeviceStateChangedCallback(), ob::VideoStreamProfile::setDistortion(), ob::Context::setExtensionsDirectory(), ob::Device::setFloatProperty(), ob::Config::setFrameAggregateOutputMode(), ob::FrameHelper::setFrameDeviceTimestampUs(), ob::Device::setIntProperty(), ob::VideoStreamProfile::setIntrinsic(), ob::Context::setLoggerFileName(), ob::Context::setLoggerSeverity(), ob::Context::setLoggerToCallback(), ob::Context::setLoggerToConsole(), ob::Context::setLoggerToFile(), ob::Device::setMultiDeviceSyncConfig(), ob::VideoFrame::setPixelAvailableBitSize(), ob::VideoFrame::setPixelType(), ob::PlaybackDevice::setPlaybackRate(), ob::PlaybackDevice::setPlaybackStatusChangeCallback(), ob::Frame::setStreamProfile(), ob::Device::setStructuredData(), ob::Frame::setSystemTimestampUs(), ob::Device::setTimestampResetConfig(), ob::Context::setUvcBackendType(), ob::DepthFrame::setValueScale(), ob::SpatialAdvancedFilter::SpatialAdvancedFilter(), ob::SpatialFastFilter::SpatialFastFilter(), ob::SpatialModerateFilter::SpatialModerateFilter(), ob::Pipeline::start(), ob::Pipeline::start(), ob::Sensor::start(), ob::Pipeline::stop(), ob::Sensor::stop(), ob::Device::switchDepthWorkMode(), ob::Device::switchDepthWorkMode(), ob::Sensor::switchProfile(), ob::TemporalFilter::TemporalFilter(), ob::ThresholdFilter::ThresholdFilter(), ob::Device::timerSyncWithHost(), ob::Device::timestampReset(), ob::CoordinateTransformHelper::transformation2dto2d(), ob::CoordinateTransformHelper::transformation2dto3d(), ob::CoordinateTransformHelper::transformation3dto2d(), ob::CoordinateTransformHelper::transformation3dto3d(), ob::CoordinateTransformHelper::transformationDepthFrameToColorCamera(), ob::CoordinateTransformHelper::transformationDepthToPointCloud(), ob::CoordinateTransformHelper::transformationDepthToRGBDPointCloud(), ob::CoordinateTransformHelper::transformationInitXYTables(), ob::Device::triggerCapture(), ob::Context::unregisterDeviceChangedCallback(), ob::Frame::updateData(), ob::Device::updateFirmware(), ob::Device::updateFirmwareFromData(), ob::Frame::updateMetadata(), ob::Device::updateOptionalDepthPresets(), ob::Pipeline::waitForFrameset(), ob::Device::writeCustomerData(), ob::CameraParamList::~CameraParamList(), ob::Config::~Config(), ob::Context::~Context(), ob::Device::~Device(), ob::DeviceFrameInterleaveList::~DeviceFrameInterleaveList(), ob::DeviceInfo::~DeviceInfo(), ob::DeviceList::~DeviceList(), ob::DevicePresetList::~DevicePresetList(), ob::Filter::~Filter(), ob::Frame::~Frame(), ob::OBDepthWorkModeList::~OBDepthWorkModeList(), ob::OBFilterList::~OBFilterList(), ob::Pipeline::~Pipeline(), ob::PresetResolutionConfigList::~PresetResolutionConfigList(), ob::RecordDevice::~RecordDevice(), ob::Sensor::~Sensor(), ob::SensorList::~SensorList(), ob::StreamProfile::~StreamProfile(), and ob::StreamProfileList::~StreamProfileList().
what()
const char * ob::Error::what () const inline override noexcept
Returns the error message of the exception.
Returns
const char* The error message.
Definition at line 67 of file Error.hpp.
getExceptionType()
OBExceptionType ob::Error::getExceptionType () const inline noexcept
Returns the exception type of the exception.
Read the comments of the OBExceptionType enum in the libobsensor/h/ObTypes.h file for more information.
Returns
OBExceptionType The exception type.
Definition at line 77 of file Error.hpp.
getFunction()
const char * ob::Error::getFunction () const inline noexcept
Returns the name of the function where the exception occurred.
Returns
const char* The function name.
Definition at line 86 of file Error.hpp.
getArgs()
const char * ob::Error::getArgs () const inline noexcept
Returns the arguments of the function where the exception occurred.
Returns
const char* The arguments.
Definition at line 95 of file Error.hpp.
getMessage()
const char * ob::Error::getMessage () const inline noexcept
Returns the error message of the exception.
It is recommended to use the what() function instead.
Returns
const char* The error message.
Definition at line 105 of file Error.hpp.
getName()
const char * ob::Error::getName () const inline noexcept
Definition at line 111 of file Error.hpp.
The documentation for this class was generated from the following file:
Error.hpp