OrbbecSDK: ob::RecordDevice Class Reference
ob::RecordDevice Class Reference
#include <RecordPlayback.hpp>
Public Member Functions
RecordDevice (std::shared_ptr< Device > device, const std::string &file, bool compressionEnabled=true)
virtual ~RecordDevice () noexcept
RecordDevice (RecordDevice &&other) noexcept
RecordDevice & operator= (RecordDevice &&other) noexcept
RecordDevice (const RecordDevice &)=delete
RecordDevice & operator= (const RecordDevice &)=delete
void pause ()
void resume ()
Detailed Description
Definition at line 21 of file RecordPlayback.hpp.
Constructor & Destructor Documentation
RecordDevice() [1/3]
ob::RecordDevice::RecordDevice (std::shared_ptr< Device > device, const std::string & file, bool compressionEnabled = true) inline explicit
Definition at line 26 of file RecordPlayback.hpp.
Referenced by operator=(), operator=(), RecordDevice(), and RecordDevice().
~RecordDevice()
virtual ob::RecordDevice::~RecordDevice () inline virtual noexcept
Definition at line 32 of file RecordPlayback.hpp.
RecordDevice() [2/3]
ob::RecordDevice::RecordDevice (RecordDevice && other) inline noexcept
Definition at line 38 of file RecordPlayback.hpp.
RecordDevice() [3/3]
ob::RecordDevice::RecordDevice (const RecordDevice &) delete
Member Function Documentation
operator=() [1/2]
RecordDevice & ob::RecordDevice::operator= (RecordDevice && other) inline noexcept
Definition at line 45 of file RecordPlayback.hpp.
operator=() [2/2]
RecordDevice & ob::RecordDevice::operator= (const RecordDevice &) delete
pause()
void ob::RecordDevice::pause () inline
Definition at line 58 of file RecordPlayback.hpp.
resume()
void ob::RecordDevice::resume () inline
Definition at line 64 of file RecordPlayback.hpp.
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/RecordPlayback.hpp