OrbbecSDK: ob::VideoStreamProfile Class Reference
ob::VideoStreamProfile Class Reference
Class representing a video stream profile.
#include <StreamProfile.hpp>
Public Member Functions
VideoStreamProfile (const ob_stream_profile_t *impl)
~VideoStreamProfile () noexcept override=default
uint32_t getFps () const
Return the frame rate of the stream.
uint32_t getWidth () const
Return the width of the stream.
uint32_t getHeight () const
Return the height of the stream.
OBCameraIntrinsic getIntrinsic () const
Get the intrinsic parameters of the stream.
void setIntrinsic (const OBCameraIntrinsic &intrinsic)
Set the intrinsic parameters of the stream.
OBCameraDistortion getDistortion () const
Get the distortion parameters of the stream.
void setDistortion (const OBCameraDistortion &distortion)
Set the distortion parameters of the stream.
uint32_t fps () const
uint32_t width () const
uint32_t height () const
Public Member Functions inherited from ob::StreamProfile
StreamProfile (StreamProfile &streamProfile)=delete
StreamProfile & operator= (StreamProfile &streamProfile)=delete
StreamProfile (StreamProfile &&streamProfile) noexcept
StreamProfile & operator= (StreamProfile &&streamProfile) noexcept
virtual ~StreamProfile () noexcept
const ob_stream_profile * getImpl () const
OBFormat getFormat () const
Get the format of the stream.
OBStreamType getType () const
Get the type of stream.
OBExtrinsic getExtrinsicTo (std::shared_ptr< StreamProfile > target) const
Get the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (std::shared_ptr< StreamProfile > target, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (const OBStreamType &targetStreamType, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream type.
template<typename T>
bool is () const
Check if frame object is compatible with the given type.
template<typename T>
std::shared_ptr< T > as ()
Converts object type to target type.
template<typename T>
std::shared_ptr< const T > as () const
Converts object type to target type (const version).
OBFormat format () const
OBStreamType type () const
Additional Inherited Members
Protected Member Functions inherited from ob::StreamProfile
StreamProfile (const ob_stream_profile_t *impl)
Protected Attributes inherited from ob::StreamProfile
const ob_stream_profile_t * impl_ = nullptr
Detailed Description
Class representing a video stream profile.
Definition at line 165 of file StreamProfile.hpp.
Constructor & Destructor Documentation
VideoStreamProfile()
ob::VideoStreamProfile::VideoStreamProfile (const ob_stream_profile_t * impl) inline explicit
Definition at line 167 of file StreamProfile.hpp.
~VideoStreamProfile()
ob::VideoStreamProfile::~VideoStreamProfile () override default noexcept
Member Function Documentation
getFps()
uint32_t ob::VideoStreamProfile::getFps () const inline
Return the frame rate of the stream.
Returns
uint32_t Return the frame rate of the stream.
Definition at line 176 of file StreamProfile.hpp.
Referenced by fps(), and getFps().
getWidth()
uint32_t ob::VideoStreamProfile::getWidth () const inline
Return the width of the stream.
Returns
uint32_t Return the width of the stream.
Definition at line 188 of file StreamProfile.hpp.
Referenced by width().
getHeight()
uint32_t ob::VideoStreamProfile::getHeight () const inline
Return the height of the stream.
Returns
uint32_t Return the height of the stream.
Definition at line 200 of file StreamProfile.hpp.
Referenced by height().
getIntrinsic()
OBCameraIntrinsic ob::VideoStreamProfile::getIntrinsic () const inline
Get the intrinsic parameters of the stream.
Returns
OBCameraIntrinsic Return the intrinsic parameters.
Definition at line 212 of file StreamProfile.hpp.
setIntrinsic()
void ob::VideoStreamProfile::setIntrinsic (const OBCameraIntrinsic & intrinsic) inline
Set the intrinsic parameters of the stream.
Parameters
intrinsic The intrinsic parameters.
Definition at line 224 of file StreamProfile.hpp.
getDistortion()
OBCameraDistortion ob::VideoStreamProfile::getDistortion () const inline
Get the distortion parameters of the stream.
Brown distortion model
Returns
OBCameraDistortion Return the distortion parameters.
Definition at line 236 of file StreamProfile.hpp.
setDistortion()
void ob::VideoStreamProfile::setDistortion (const OBCameraDistortion & distortion) inline
Set the distortion parameters of the stream.
Parameters
distortion The distortion parameters.
Definition at line 248 of file StreamProfile.hpp.
fps()
uint32_t ob::VideoStreamProfile::fps () const inline
Definition at line 256 of file StreamProfile.hpp.
Referenced by getFps().
width()
uint32_t ob::VideoStreamProfile::width () const inline
Definition at line 260 of file StreamProfile.hpp.
Referenced by getWidth().
height()
uint32_t ob::VideoStreamProfile::height () const inline
Definition at line 264 of file StreamProfile.hpp.
Referenced by getHeight().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/StreamProfile.hpp