OrbbecSDK: ob::StreamProfile Class Reference
ob::StreamProfile Class Reference
#include <StreamProfile.hpp>
Public Member Functions
StreamProfile (StreamProfile &streamProfile)=delete
StreamProfile & operator= (StreamProfile &streamProfile)=delete
StreamProfile (StreamProfile &&streamProfile) noexcept
StreamProfile & operator= (StreamProfile &&streamProfile) noexcept
virtual ~StreamProfile () noexcept
const ob_stream_profile * getImpl () const
OBFormat getFormat () const
Get the format of the stream.
OBStreamType getType () const
Get the type of stream.
OBExtrinsic getExtrinsicTo (std::shared_ptr< StreamProfile > target) const
Get the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (std::shared_ptr< StreamProfile > target, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (const OBStreamType &targetStreamType, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream type.
template<typename T>
bool is () const
Check if frame object is compatible with the given type.
template<typename T>
std::shared_ptr< T > as ()
Converts object type to target type.
template<typename T>
std::shared_ptr< const T > as () const
Converts object type to target type (const version).
OBFormat format () const
OBStreamType type () const
Protected Member Functions
StreamProfile (const ob_stream_profile_t *impl)
Protected Attributes
const ob_stream_profile_t * impl_ = nullptr
Detailed Description
Definition at line 18 of file StreamProfile.hpp.
Constructor & Destructor Documentation
StreamProfile() [1/3]
ob::StreamProfile::StreamProfile (StreamProfile & streamProfile) delete
Referenced by ob::AccelStreamProfile::AccelStreamProfile(), ob::GyroStreamProfile::GyroStreamProfile(), operator=(), operator=(), StreamProfile(), StreamProfile(), and ob::VideoStreamProfile::VideoStreamProfile().
StreamProfile() [2/3]
ob::StreamProfile::StreamProfile (StreamProfile && streamProfile) inline noexcept
Definition at line 26 of file StreamProfile.hpp.
~StreamProfile()
virtual ob::StreamProfile::~StreamProfile () inline virtual noexcept
Definition at line 41 of file StreamProfile.hpp.
StreamProfile() [3/3]
ob::StreamProfile::StreamProfile (const ob_stream_profile_t * impl) inline explicit protected
Definition at line 159 of file StreamProfile.hpp.
Member Function Documentation
operator=() [1/2]
StreamProfile & ob::StreamProfile::operator= (StreamProfile & streamProfile) delete
operator=() [2/2]
StreamProfile & ob::StreamProfile::operator= (StreamProfile && streamProfile) inline noexcept
Definition at line 30 of file StreamProfile.hpp.
getImpl()
const ob_stream_profile * ob::StreamProfile::getImpl () const inline
Definition at line 49 of file StreamProfile.hpp.
getFormat()
OBFormat ob::StreamProfile::getFormat () const inline
Get the format of the stream.
Returns
OBFormat return the format of the stream.
Definition at line 58 of file StreamProfile.hpp.
Referenced by format().
getType()
OBStreamType ob::StreamProfile::getType () const inline
Get the type of stream.
Returns
OBStreamType return the type of the stream.
Definition at line 70 of file StreamProfile.hpp.
Referenced by is(), and type().
getExtrinsicTo()
OBExtrinsic ob::StreamProfile::getExtrinsicTo (std::shared_ptr< StreamProfile > target) const inline
Get the extrinsic parameters from current stream profile to the given target stream profile.
Returns
OBExtrinsic Return the extrinsic parameters.
Definition at line 82 of file StreamProfile.hpp.
bindExtrinsicTo() [1/2]
void ob::StreamProfile::bindExtrinsicTo (std::shared_ptr< StreamProfile > target, const OBExtrinsic & extrinsic) inline
Set the extrinsic parameters from current stream profile to the given target stream profile.
Template Parameters
target Target stream profile.
extrinsic The extrinsic.
Definition at line 95 of file StreamProfile.hpp.
bindExtrinsicTo() [2/2]
void ob::StreamProfile::bindExtrinsicTo (const OBStreamType & targetStreamType, const OBExtrinsic & extrinsic) inline
Set the extrinsic parameters from current stream profile to the given target stream type.
Template Parameters
targetStreamType Target stream type.
extrinsic The extrinsic.
Definition at line 107 of file StreamProfile.hpp.
is()
template<typename T> bool ob::StreamProfile::is () const
Check if frame object is compatible with the given type.
Template Parameters
T Given type.
Returns
bool return result.
Definition at line 381 of file StreamProfile.hpp.
Referenced by as(), and as().
as() [1/2]
template<typename T> std::shared_ptr< T > ob::StreamProfile::as () inline
Converts object type to target type.
Template Parameters
T Target type.
Returns
std::shared_ptr<T> Return the result. Throws an exception if conversion is not possible.
Definition at line 127 of file StreamProfile.hpp.
as() [2/2]
template<typename T> std::shared_ptr< const T > ob::StreamProfile::as () const inline
Converts object type to target type (const version).
Template Parameters
T Target type.
Returns
std::shared_ptr<T> Return the result. Throws an exception if conversion is not possible.
Definition at line 141 of file StreamProfile.hpp.
format()
OBFormat ob::StreamProfile::format () const inline
Definition at line 150 of file StreamProfile.hpp.
Referenced by getFormat().
type()
OBStreamType ob::StreamProfile::type () const inline
Definition at line 154 of file StreamProfile.hpp.
Referenced by getType().
Member Data Documentation
impl_
const ob_stream_profile_t* ob::StreamProfile::impl_ = nullptr protected
Definition at line 20 of file StreamProfile.hpp.
Referenced by bindExtrinsicTo(), bindExtrinsicTo(), ob::VideoStreamProfile::getDistortion(), getExtrinsicTo(), getFormat(), ob::VideoStreamProfile::getFps(), ob::AccelStreamProfile::getFullScaleRange(), ob::GyroStreamProfile::getFullScaleRange(), ob::VideoStreamProfile::getHeight(), getImpl(), ob::AccelStreamProfile::getIntrinsic(), ob::GyroStreamProfile::getIntrinsic(), ob::VideoStreamProfile::getIntrinsic(), ob::AccelStreamProfile::getSampleRate(), ob::GyroStreamProfile::getSampleRate(), getType(), ob::VideoStreamProfile::getWidth(), operator=(), ob::VideoStreamProfile::setDistortion(), ob::VideoStreamProfile::setIntrinsic(), StreamProfile(), and ~StreamProfile().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/StreamProfile.hpp