OrbbecSDK: ob::DeviceInfo Class Reference
ob::DeviceInfo Class Reference
A class describing device information, representing the name, id, serial number and other basic information of an RGBD camera.
#include <Device.hpp>
Public Member Functions
DeviceInfo (ob_device_info_t *impl)
~DeviceInfo () noexcept
const char * getName () const
Get device name.
int getPid () const
Get the pid of the device.
int getVid () const
Get the vid of the device.
const char * getUid () const
Get system assigned uid for distinguishing between different devices.
const char * getSerialNumber () const
Get the serial number of the device.
const char * getFirmwareVersion () const
Get the version number of the firmware.
const char * getConnectionType () const
Get the connection type of the device.
const char * getIpAddress () const
Get the IP address of the device.
const char * getHardwareVersion () const
Get the version number of the hardware.
const char * getSupportedMinSdkVersion () const
Get the minimum version number of the SDK supported by the device.
const char * getAsicName () const
Get chip type name.
OBDeviceType getDeviceType () const
Get the device type.
const char * name () const
int pid () const
int vid () const
const char * uid () const
const char * serialNumber () const
const char * firmwareVersion () const
const char * connectionType () const
const char * ipAddress () const
const char * hardwareVersion () const
const char * supportedMinSdkVersion () const
const char * asicName () const
OBDeviceType deviceType () const
Detailed Description
A class describing device information, representing the name, id, serial number and other basic information of an RGBD camera.
Definition at line 872 of file Device.hpp.
Constructor & Destructor Documentation
DeviceInfo()
ob::DeviceInfo::DeviceInfo (ob_device_info_t * impl) inline explicit
Definition at line 877 of file Device.hpp.
~DeviceInfo()
ob::DeviceInfo::~DeviceInfo () inline noexcept
Definition at line 878 of file Device.hpp.
Member Function Documentation
getName()
const char * ob::DeviceInfo::getName () const inline
Get device name.
Returns
const char * return the device name
Definition at line 889 of file Device.hpp.
Referenced by name().
getPid()
int ob::DeviceInfo::getPid () const inline
Get the pid of the device.
Returns
int return the pid of the device
Definition at line 901 of file Device.hpp.
Referenced by pid().
getVid()
int ob::DeviceInfo::getVid () const inline
Get the vid of the device.
Returns
int return the vid of the device
Definition at line 913 of file Device.hpp.
Referenced by vid().
getUid()
const char * ob::DeviceInfo::getUid () const inline
Get system assigned uid for distinguishing between different devices.
Returns
const char * return the uid of the device
Definition at line 925 of file Device.hpp.
Referenced by uid().
getSerialNumber()
const char * ob::DeviceInfo::getSerialNumber () const inline
Get the serial number of the device.
Returns
const char * return the serial number of the device
Definition at line 937 of file Device.hpp.
Referenced by serialNumber().
getFirmwareVersion()
const char * ob::DeviceInfo::getFirmwareVersion () const inline
Get the version number of the firmware.
Returns
const char* return the version number of the firmware
Definition at line 949 of file Device.hpp.
Referenced by firmwareVersion().
getConnectionType()
const char * ob::DeviceInfo::getConnectionType () const inline
Get the connection type of the device.
Returns
const char* the connection type of the device, currently supports: "USB", "USB1.0", "USB1.1", "USB2.0", "USB2.1", "USB3.0", "USB3.1", "USB3.2", "Ethernet"
Definition at line 962 of file Device.hpp.
Referenced by connectionType().
getIpAddress()
const char * ob::DeviceInfo::getIpAddress () const inline
Get the IP address of the device.
Attention
Only valid for network devices, otherwise it will return "0.0.0.0".
Returns
const char* the IP address of the device, such as "192.168.1.10"
Definition at line 976 of file Device.hpp.
Referenced by ipAddress().
getHardwareVersion()
const char * ob::DeviceInfo::getHardwareVersion () const inline
Get the version number of the hardware.
Returns
const char* the version number of the hardware
Definition at line 988 of file Device.hpp.
Referenced by hardwareVersion().
getSupportedMinSdkVersion()
const char * ob::DeviceInfo::getSupportedMinSdkVersion () const inline
Get the minimum version number of the SDK supported by the device.
Returns
const char* the minimum SDK version number supported by the device
Definition at line 1000 of file Device.hpp.
Referenced by supportedMinSdkVersion().
getAsicName()
const char * ob::DeviceInfo::getAsicName () const inline
Get chip type name.
Returns
const char* the chip type name
Definition at line 1012 of file Device.hpp.
Referenced by asicName().
getDeviceType()
OBDeviceType ob::DeviceInfo::getDeviceType () const inline
Get the device type.
Returns
OBDeviceType the device type
Definition at line 1024 of file Device.hpp.
Referenced by deviceType().
name()
const char * ob::DeviceInfo::name () const inline
Definition at line 1033 of file Device.hpp.
Referenced by getAsicName(), and getName().
pid()
int ob::DeviceInfo::pid () const inline
Definition at line 1037 of file Device.hpp.
Referenced by getPid().
vid()
int ob::DeviceInfo::vid () const inline
Definition at line 1041 of file Device.hpp.
Referenced by getVid().
uid()
const char * ob::DeviceInfo::uid () const inline
Definition at line 1045 of file Device.hpp.
Referenced by getUid().
serialNumber()
const char * ob::DeviceInfo::serialNumber () const inline
Definition at line 1049 of file Device.hpp.
firmwareVersion()
const char * ob::DeviceInfo::firmwareVersion () const inline
Definition at line 1053 of file Device.hpp.
connectionType()
const char * ob::DeviceInfo::connectionType () const inline
Definition at line 1057 of file Device.hpp.
ipAddress()
const char * ob::DeviceInfo::ipAddress () const inline
Definition at line 1061 of file Device.hpp.
hardwareVersion()
const char * ob::DeviceInfo::hardwareVersion () const inline
Definition at line 1065 of file Device.hpp.
supportedMinSdkVersion()
const char * ob::DeviceInfo::supportedMinSdkVersion () const inline
Definition at line 1069 of file Device.hpp.
asicName()
const char * ob::DeviceInfo::asicName () const inline
Definition at line 1073 of file Device.hpp.
deviceType()
OBDeviceType ob::DeviceInfo::deviceType () const inline
Definition at line 1077 of file Device.hpp.
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/Device.hpp