OrbbecSDK: ob::SensorList Class Reference
ob::SensorList Class Reference
#include <Sensor.hpp>
Public Member Functions
SensorList (ob_sensor_list_t *impl)
~SensorList () noexcept
uint32_t getCount () const
Get the number of sensors.
OBSensorType getSensorType (uint32_t index) const
Get the type of the specified sensor.
std::shared_ptr< Sensor > getSensor (uint32_t index) const
Get a sensor by index number.
std::shared_ptr< Sensor > getSensor (OBSensorType sensorType) const
Get a sensor by sensor type.
uint32_t count () const
OBSensorType type (uint32_t index) const
Detailed Description
Definition at line 160 of file Sensor.hpp.
Constructor & Destructor Documentation
SensorList()
ob::SensorList::SensorList (ob_sensor_list_t * impl) inline explicit
Definition at line 165 of file Sensor.hpp.
~SensorList()
ob::SensorList::~SensorList () inline noexcept
Definition at line 167 of file Sensor.hpp.
Member Function Documentation
getCount()
uint32_t ob::SensorList::getCount () const inline
Get the number of sensors.
Returns
uint32_t The number of sensors.
Definition at line 178 of file Sensor.hpp.
Referenced by count().
getSensorType()
OBSensorType ob::SensorList::getSensorType (uint32_t index) const inline
Get the type of the specified sensor.
Parameters
index The sensor index.
Returns
OBSensorType The sensor type.
Definition at line 191 of file Sensor.hpp.
Referenced by type().
getSensor() [1/2]
std::shared_ptr< Sensor > ob::SensorList::getSensor (uint32_t index) const inline
Get a sensor by index number.
Parameters
index The sensor index. The range is [0, count-1]. If the index exceeds the range, an exception will be thrown.
Returns
std::shared_ptr<Sensor> The sensor object.
Definition at line 204 of file Sensor.hpp.
getSensor() [2/2]
std::shared_ptr< Sensor > ob::SensorList::getSensor (OBSensorType sensorType) const inline
Get a sensor by sensor type.
Parameters
sensorType The sensor type to obtain.
Returns
std::shared_ptr<Sensor> A sensor object. If the specified sensor type does not exist, it will return empty.
Definition at line 217 of file Sensor.hpp.
count()
uint32_t ob::SensorList::count () const inline
Definition at line 226 of file Sensor.hpp.
Referenced by getCount().
type()
OBSensorType ob::SensorList::type (uint32_t index) const inline
Definition at line 230 of file Sensor.hpp.
Referenced by getSensorType().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/Sensor.hpp