OrbbecSDK: ob::GyroStreamProfile Class Reference
ob::GyroStreamProfile Class Reference
Class representing a gyroscope stream profile.
#include <StreamProfile.hpp>
Public Member Functions
GyroStreamProfile (const ob_stream_profile_t *impl)
~GyroStreamProfile () noexcept override=default
OBGyroFullScaleRange getFullScaleRange () const
Return the full scale range.
OBGyroSampleRate getSampleRate () const
Return the sampling frequency.
OBGyroIntrinsic getIntrinsic () const
get the intrinsic parameters of the stream.
OBGyroFullScaleRange fullScaleRange () const
OBGyroSampleRate sampleRate () const
Public Member Functions inherited from ob::StreamProfile
StreamProfile (StreamProfile &streamProfile)=delete
StreamProfile & operator= (StreamProfile &streamProfile)=delete
StreamProfile (StreamProfile &&streamProfile) noexcept
StreamProfile & operator= (StreamProfile &&streamProfile) noexcept
virtual ~StreamProfile () noexcept
const ob_stream_profile * getImpl () const
OBFormat getFormat () const
Get the format of the stream.
OBStreamType getType () const
Get the type of stream.
OBExtrinsic getExtrinsicTo (std::shared_ptr< StreamProfile > target) const
Get the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (std::shared_ptr< StreamProfile > target, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream profile.
void bindExtrinsicTo (const OBStreamType &targetStreamType, const OBExtrinsic &extrinsic)
Set the extrinsic parameters from current stream profile to the given target stream type.
template<typename T>
bool is () const
Check if frame object is compatible with the given type.
template<typename T>
std::shared_ptr< T > as ()
Converts object type to target type.
template<typename T>
std::shared_ptr< const T > as () const
Converts object type to target type (const version).
OBFormat format () const
OBStreamType type () const
Additional Inherited Members
Protected Member Functions inherited from ob::StreamProfile
StreamProfile (const ob_stream_profile_t *impl)
Protected Attributes inherited from ob::StreamProfile
const ob_stream_profile_t * impl_ = nullptr
Detailed Description
Class representing a gyroscope stream profile.
Definition at line 328 of file StreamProfile.hpp.
Constructor & Destructor Documentation
GyroStreamProfile()
ob::GyroStreamProfile::GyroStreamProfile (const ob_stream_profile_t * impl) inline explicit
Definition at line 330 of file StreamProfile.hpp.
~GyroStreamProfile()
ob::GyroStreamProfile::~GyroStreamProfile () override default noexcept
Member Function Documentation
getFullScaleRange()
OBGyroFullScaleRange ob::GyroStreamProfile::getFullScaleRange () const inline
Return the full scale range.
Returns
OBAccelFullScaleRange Return the scale range value.
Definition at line 339 of file StreamProfile.hpp.
Referenced by fullScaleRange(), and getFullScaleRange().
getSampleRate()
OBGyroSampleRate ob::GyroStreamProfile::getSampleRate () const inline
Return the sampling frequency.
Returns
OBAccelFullScaleRange Return the sampling frequency.
Definition at line 351 of file StreamProfile.hpp.
Referenced by sampleRate().
getIntrinsic()
OBGyroIntrinsic ob::GyroStreamProfile::getIntrinsic () const inline
get the intrinsic parameters of the stream.
Returns
OBGyroIntrinsic Return the intrinsic parameters.
Definition at line 363 of file StreamProfile.hpp.
fullScaleRange()
OBGyroFullScaleRange ob::GyroStreamProfile::fullScaleRange () const inline
Definition at line 372 of file StreamProfile.hpp.
Referenced by getFullScaleRange().
sampleRate()
OBGyroSampleRate ob::GyroStreamProfile::sampleRate () const inline
Definition at line 376 of file StreamProfile.hpp.
Referenced by getSampleRate().
The documentation for this class was generated from the following file:
E:/code/orbbsdk_group/OpenOrbbecSDK/include/libobsensor/hpp/StreamProfile.hpp