OrbbecSDK: ob Namespace Reference
ob Namespace Reference
Classes
class AccelFrame
Define the AccelFrame class, which inherits from the Frame class.
class AccelStreamProfile
Class representing an accelerometer stream profile.
class Align
Align for depth to other or other to depth.
class CameraParamList
Class representing a list of camera parameters.
class ColorFrame
Define the ColorFrame class, which inherits from the VideoFrame classd.
class ConfidenceFrame
Define the ConfidenceFrame class, which inherits from the VideoFrame class.
class Config
Config class for configuring pipeline parameters.
class Context
class CoordinateTransformHelper
class DecimationFilter
Decimation filter, reducing complexity by subsampling depth maps and losing depth details.
class DepthFrame
Define the DepthFrame class, which inherits from the VideoFrame class.
class Device
class DeviceFrameInterleaveList
Class representing a list of device Frame Interleave.
class DeviceInfo
A class describing device information, representing the name, id, serial number and other basic information of an RGBD camera.
class DeviceList
Class representing a list of devices.
class DevicePresetList
Class representing a list of device presets.
class DisparityTransform
Depth to disparity or disparity to depth.
class Error
class Filter
The Filter class is the base class for all filters in the SDK.
class FilterFactory
A factory class for creating filters.
class FormatConvertFilter
The FormatConvertFilter class is a subclass of Filter that performs format conversion.
class Frame
Define the frame class, which is the base class of all frame types.
class FrameFactory
FrameFactory class, which provides some static functions to create frame objects.
class FrameHelper
FrameHepler class, which provides some static functions to set timestamp for frame objects FrameHepler inherited from the FrameFactory and the timestamp interface implement here both for compatibility purposes.
class FrameSet
Define the FrameSet class, which inherits from the Frame class.
class GyroFrame
Define the GyroFrame class, which inherits from the Frame class.
class GyroStreamProfile
Class representing a gyroscope stream profile.
class HdrMerge
HdrMerge processing block, the processing merges between depth frames with different sub-preset sequence ids.
class HoleFillingFilter
Hole filling filter,the processing performed depends on the selected hole filling mode.
class IRFrame
Define the IRFrame class, which inherits from the VideoFrame class.
class NoiseRemovalFilter
The noise removal filter,removing scattering depth pixels.
class OBDepthWorkModeList
class OBFilterList
class Pipeline
class PlaybackDevice
class PointCloudFilter
The PointCloudFilter class is a subclass of Filter that generates point clouds.
class PointCloudHelper
class PointsFrame
Define the PointsFrame class, which inherits from the Frame class.
class PresetResolutionConfigeList
Class representing a list of device Frame Interleave.
struct RangeTraits
Get the type of a PropertyRange member.
struct RangeTraits< OBFloatPropertyRange >
struct RangeTraits< OBIntPropertyRange >
struct RangeTraits< OBUint16PropertyRange >
struct RangeTraits< OBUint8PropertyRange >
class RecordDevice
class Sensor
class SensorList
class SequenceIdFilter
Create SequenceIdFilter processing block.
class SpatialAdvancedFilter
Spatial advanced filte smooths the image by calculating frame with alpha and delta settings alpha defines the weight of the current pixel for smoothing, delta defines the depth gradient below which the smoothing will occur as number of depth levels.
class StreamProfile
class StreamProfileFactory
class StreamProfileList
class TemporalFilter
Temporal filter.
class ThresholdFilter
Creates depth Thresholding filter By controlling min and max options on the block.
class TypeHelper
class Version
class VideoFrame
Define the VideoFrame class, which inherits from the Frame class.
class VideoStreamProfile
Class representing a video stream profile.
Typedefs
typedef std::function< void(std::shared_ptr< Frame >)> FilterCallback
A callback function that takes a shared pointer to a Frame object as its argument.
typedef std::function< void(OBPlaybackStatus status)> PlaybackStatusChangeCallback
Functions
template<typename T>
T getPropertyRange (const OBFilterConfigSchemaItem &item, const double cur)
Get T Property Range.
Detailed Description
Frame classis inheritance hierarchy: Frame | +--------—+-------—+-------—+--------—+ | | | | | VideoFrame PointsFrame AccelFrame GyroFrame FrameSet | +-—+-------—+----------------—+ | | | ColorFrame DepthFrame IRFrame | +--—+--—+ | | IRLeftFrame IRRightFrame
Typedef Documentation
FilterCallback
typedef std::function<void(std::shared_ptr<Frame>)> ob::FilterCallback
A callback function that takes a shared pointer to a Frame object as its argument.
Definition at line 32 of file Filter.hpp.
PlaybackStatusChangeCallback
typedef std::function<void(OBPlaybackStatus status)> ob::PlaybackStatusChangeCallback
Definition at line 19 of file RecordPlayback.hpp.
Function Documentation
getPropertyRange()
template<typename T> T ob::getPropertyRange (const OBFilterConfigSchemaItem & item, const double cur)
Get T Property Range.
Definition at line 60 of file Filter.hpp.
Referenced by ob::SpatialAdvancedFilter::getAlphaRange(), ob::TemporalFilter::getDiffScaleRange(), ob::NoiseRemovalFilter::getDispDiffRange(), ob::SpatialAdvancedFilter::getDispDiffRange(), ob::SpatialAdvancedFilter::getMagnitudeRange(), ob::ThresholdFilter::getMaxRange(), ob::NoiseRemovalFilter::getMaxSizeRange(), ob::ThresholdFilter::getMinRange(), ob::SpatialAdvancedFilter::getRadiusRange(), ob::DecimationFilter::getScaleRange(), and ob::TemporalFilter::getWeightRange().