var annotated_dup =
[
    [ "k4a", null, [
      [ "calibration", "structk4a_1_1calibration.html", "structk4a_1_1calibration" ],
      [ "capture", "classk4a_1_1capture.html", "classk4a_1_1capture" ],
      [ "data_block", "classk4a_1_1data__block.html", "classk4a_1_1data__block" ],
      [ "device", "classk4a_1_1device.html", "classk4a_1_1device" ],
      [ "error", "classk4a_1_1error.html", null ],
      [ "image", "classk4a_1_1image.html", "classk4a_1_1image" ],
      [ "playback", "classk4a_1_1playback.html", "classk4a_1_1playback" ],
      [ "record", "classk4a_1_1record.html", "classk4a_1_1record" ],
      [ "transformation", "classk4a_1_1transformation.html", "classk4a_1_1transformation" ]
    ] ],
    [ "_k4a_calibration_camera_t", "struct__k4a__calibration__camera__t.html", "struct__k4a__calibration__camera__t" ],
    [ "_k4a_calibration_extrinsics_t", "struct__k4a__calibration__extrinsics__t.html", "struct__k4a__calibration__extrinsics__t" ],
    [ "_k4a_calibration_intrinsics_t", "struct__k4a__calibration__intrinsics__t.html", "struct__k4a__calibration__intrinsics__t" ],
    [ "_k4a_calibration_t", "struct__k4a__calibration__t.html", "struct__k4a__calibration__t" ],
    [ "_k4a_device_configuration_t", "struct__k4a__device__configuration__t.html", "struct__k4a__device__configuration__t" ],
    [ "_k4a_hardware_version_t", "struct__k4a__hardware__version__t.html", "struct__k4a__hardware__version__t" ],
    [ "_k4a_imu_sample_t", "struct__k4a__imu__sample__t.html", "struct__k4a__imu__sample__t" ],
    [ "_k4a_record_configuration_t", "struct__k4a__record__configuration__t.html", "struct__k4a__record__configuration__t" ],
    [ "_k4a_record_subtitle_settings_t", "struct__k4a__record__subtitle__settings__t.html", "struct__k4a__record__subtitle__settings__t" ],
    [ "_k4a_record_video_settings_t", "struct__k4a__record__video__settings__t.html", "struct__k4a__record__video__settings__t" ],
    [ "_k4a_version_t", "struct__k4a__version__t.html", "struct__k4a__version__t" ],
    [ "k4a_calibration_intrinsic_parameters_t", "unionk4a__calibration__intrinsic__parameters__t.html", "unionk4a__calibration__intrinsic__parameters__t" ],
    [ "k4a_capture_t", "classk4a__capture__t.html", "classk4a__capture__t" ],
    [ "k4a_device_t", "classk4a__device__t.html", "classk4a__device__t" ],
    [ "k4a_float2_t", "unionk4a__float2__t.html", "unionk4a__float2__t" ],
    [ "k4a_float3_t", "unionk4a__float3__t.html", "unionk4a__float3__t" ],
    [ "k4a_image_t", "classk4a__image__t.html", "classk4a__image__t" ],
    [ "k4a_playback_data_block_t", "classk4a__playback__data__block__t.html", "classk4a__playback__data__block__t" ],
    [ "k4a_playback_t", "classk4a__playback__t.html", "classk4a__playback__t" ],
    [ "k4a_record_t", "classk4a__record__t.html", "classk4a__record__t" ],
    [ "k4a_transformation_t", "classk4a__transformation__t.html", "classk4a__transformation__t" ]
];