var files_dup =
[
    [ "k4a", "dir_420081ddadc667911a8d25bb046c2bc5.html", "dir_420081ddadc667911a8d25bb046c2bc5" ],
    [ "k4arecord", "dir_ac9fb128d3f184be617d14cbff22cd8e.html", "dir_ac9fb128d3f184be617d14cbff22cd8e" ],
    [ "allocator.h", "allocator_8h.html", "allocator_8h" ],
    [ "calibration.h", "calibration_8h.html", "calibration_8h" ],
    [ "capture.h", "capture_8h.html", "capture_8h" ],
    [ "capturesync.h", "capturesync_8h.html", "capturesync_8h" ],
    [ "color.h", "color_8h.html", "color_8h" ],
    [ "color_mcu.h", "color__mcu_8h_source.html", null ],
    [ "common.h", "common_8h.html", "common_8h" ],
    [ "deloader.h", "deloader_8h.html", null ],
    [ "depth.h", "depth_8h.html", "depth_8h" ],
    [ "depth_mcu.h", "depth__mcu_8h.html", "depth__mcu_8h" ],
    [ "dewrapper.h", "dewrapper_8h.html", "dewrapper_8h" ],
    [ "dynlib.h", "dynlib_8h_source.html", null ],
    [ "firmware.h", "firmware_8h.html", "firmware_8h" ],
    [ "global.h", "global_8h.html", "global_8h" ],
    [ "handle.h", "handle_8h.html", null ],
    [ "image.h", "image_8h.html", "image_8h" ],
    [ "imu.h", "imu_8h.html", "imu_8h" ],
    [ "k4aplugin.h", "k4aplugin_8h.html", "k4aplugin_8h" ],
    [ "logging.h", "logging_8h.html", "logging_8h" ],
    [ "math.h", "math_8h.html", "math_8h" ],
    [ "matroska_common.h", "matroska__common_8h.html", "matroska__common_8h" ],
    [ "matroska_read.h", "matroska__read_8h.html", "matroska__read_8h" ],
    [ "matroska_write.h", "matroska__write_8h.html", "matroska__write_8h" ],
    [ "queue.h", "queue_8h.html", "queue_8h" ],
    [ "rwlock.h", "rwlock_8h.html", null ],
    [ "tewrapper.h", "tewrapper_8h.html", "tewrapper_8h" ],
    [ "transformation.h", "transformation_8h.html", "transformation_8h" ],
    [ "usbcommand.h", "usbcommand_8h.html", "usbcommand_8h" ]
];