var hierarchy =
[
    [ "_accelerometer_t", "struct__accelerometer__t.html", null ],
    [ "k4arecord::_block_info_t", "structk4arecord_1_1__block__info__t.html", null ],
    [ "k4arecord::_cluster_info_t", "structk4arecord_1_1__cluster__info__t.html", null ],
    [ "k4arecord::_cluster_t", "structk4arecord_1_1__cluster__t.html", null ],
    [ "_depthmcu_firmware_update_status_t", "struct__depthmcu__firmware__update__status__t.html", null ],
    [ "_depthmcu_firmware_versions_t", "struct__depthmcu__firmware__versions__t.html", null ],
    [ "_firmware_component_status_t", "struct__firmware__component__status__t.html", null ],
    [ "_firmware_package_info_t", "struct__firmware__package__info__t.html", null ],
    [ "_firmware_status_summary_t", "struct__firmware__status__summary__t.html", null ],
    [ "_guid_t", "struct__guid__t.html", null ],
    [ "_gyroscope_t", "struct__gyroscope__t.html", null ],
    [ "_imu_payload_metadata_t", "struct__imu__payload__metadata__t.html", null ],
    [ "_k4a_calibration_camera_t", "struct__k4a__calibration__camera__t.html", null ],
    [ "_k4a_calibration_extrinsics_t", "struct__k4a__calibration__extrinsics__t.html", null ],
    [ "_k4a_calibration_imu_t", "struct__k4a__calibration__imu__t.html", null ],
    [ "_k4a_calibration_intrinsics_t", "struct__k4a__calibration__intrinsics__t.html", null ],
    [ "_k4a_calibration_t", "struct__k4a__calibration__t.html", [
      [ "k4a::calibration", "structk4a_1_1calibration.html", null ]
    ] ],
    [ "_k4a_camera_calibration_mode_info_t", "struct__k4a__camera__calibration__mode__info__t.html", null ],
    [ "_k4a_depth_engine_input_frame_info_t", "struct__k4a__depth__engine__input__frame__info__t.html", null ],
    [ "_k4a_depth_engine_output_frame_info_t", "struct__k4a__depth__engine__output__frame__info__t.html", null ],
    [ "_k4a_device_configuration_t", "struct__k4a__device__configuration__t.html", null ],
    [ "_k4a_hardware_version_t", "struct__k4a__hardware__version__t.html", null ],
    [ "_k4a_imu_sample_t", "struct__k4a__imu__sample__t.html", null ],
    [ "k4arecord::_k4a_playback_context_t", "structk4arecord_1_1__k4a__playback__context__t.html", null ],
    [ "k4arecord::_k4a_playback_data_block_context_t", "structk4arecord_1_1__k4a__playback__data__block__context__t.html", null ],
    [ "_k4a_plugin_t", "struct__k4a__plugin__t.html", null ],
    [ "_k4a_record_configuration_t", "struct__k4a__record__configuration__t.html", null ],
    [ "k4arecord::_k4a_record_context_t", "structk4arecord_1_1__k4a__record__context__t.html", null ],
    [ "_k4a_record_subtitle_settings_t", "struct__k4a__record__subtitle__settings__t.html", null ],
    [ "_k4a_record_video_settings_t", "struct__k4a__record__video__settings__t.html", null ],
    [ "_k4a_transform_engine_calibration_t", "struct__k4a__transform__engine__calibration__t.html", null ],
    [ "_k4a_transformation_image_descriptor_t", "struct__k4a__transformation__image__descriptor__t.html", null ],
    [ "_k4a_transformation_pinhole_t", "struct__k4a__transformation__pinhole__t.html", null ],
    [ "_k4a_transformation_xy_tables_t", "struct__k4a__transformation__xy__tables__t.html", null ],
    [ "_k4a_version_t", "struct__k4a__version__t.html", null ],
    [ "k4arecord::_loaded_cluster_t", "structk4arecord_1_1__loaded__cluster__t.html", null ],
    [ "k4a_calibration_intrinsic_parameters_t::_param", "structk4a__calibration__intrinsic__parameters__t_1_1__param.html", null ],
    [ "_temperature_t", "struct__temperature__t.html", null ],
    [ "k4arecord::_track_data_t", "structk4arecord_1_1__track__data__t.html", null ],
    [ "k4arecord::_track_header_t", "structk4arecord_1_1__track__header__t.html", null ],
    [ "k4arecord::_track_reader_t", "structk4arecord_1_1__track__reader__t.html", null ],
    [ "k4a_float2_t::_xy", "structk4a__float2__t_1_1__xy.html", null ],
    [ "k4a_float3_t::_xyz", "structk4a__float3__t_1_1__xyz.html", null ],
    [ "k4arecord::BITMAPINFOHEADER", "structk4arecord_1_1_b_i_t_m_a_p_i_n_f_o_h_e_a_d_e_r.html", null ],
    [ "k4a::capture", "classk4a_1_1capture.html", null ],
    [ "k4a::data_block", "classk4a_1_1data__block.html", null ],
    [ "k4a::device", "classk4a_1_1device.html", null ],
    [ "k4a::image", "classk4a_1_1image.html", null ],
    [ "libebml::IOCallback", null, [
      [ "k4arecord::LargeFileIOCallback", "classk4arecord_1_1_large_file_i_o_callback.html", null ]
    ] ],
    [ "k4a_calibration_intrinsic_parameters_t", "unionk4a__calibration__intrinsic__parameters__t.html", null ],
    [ "k4a_capture_t", "classk4a__capture__t.html", null ],
    [ "k4a_device_t", "classk4a__device__t.html", null ],
    [ "k4a_float2_t", "unionk4a__float2__t.html", null ],
    [ "k4a_float3_t", "unionk4a__float3__t.html", null ],
    [ "k4a_image_t", "classk4a__image__t.html", null ],
    [ "k4a_playback_data_block_t", "classk4a__playback__data__block__t.html", null ],
    [ "k4a_playback_t", "classk4a__playback__t.html", null ],
    [ "k4a_plugin_version_t", "structk4a__plugin__version__t.html", null ],
    [ "k4a_record_t", "classk4a__record__t.html", null ],
    [ "k4a_transformation_t", "classk4a__transformation__t.html", null ],
    [ "k4arecord::matroska_imu_sample_t", "structk4arecord_1_1matroska__imu__sample__t.html", null ],
    [ "k4a::playback", "classk4a_1_1playback.html", null ],
    [ "k4a::record", "classk4a_1_1record.html", null ],
    [ "std::runtime_error", null, [
      [ "k4a::error", "classk4a_1_1error.html", null ]
    ] ],
    [ "k4a::transformation", "classk4a_1_1transformation.html", null ],
    [ "xyz_vector_t", "structxyz__vector__t.html", null ]
];